'use strict';
// All cards are local teaching props. There are no external actions.
const SHORT_INTROS={
workspace:"Your train is delayed. A confidential proposal is due at 09:00. The station Wi-Fi wants you to install settings that can change how your device connects or is managed.",
payroll:'You expected a payslip this week. This email says your salary could be delayed.',
mfa:"Three sign-in requests arrive. You did not start them. Then this caller contacts you.",
supplier:"A familiar supplier conversation asks for new bank details. A voice note sounds like your manager.",
ai:'Jamie asks for the usual update. Open the desk card below and put it on the right route.',
wrongrecipient:'You notice a staff-pay spreadsheet went to the wrong external recipient one minute ago.',
converter:'You need to convert a work document. This page wants you to change device settings.',
lost:'A colleague may have left a work laptop in a taxi. It might turn up tomorrow.',
report:'Taylor wants help reporting a mistake. Build a useful report from the clues, without blame.',
law:'A customer file went outside the business. Your manager wants to leave it until Monday.'};
const SHORT_NODES={
workspace:{private:'You check the booth, keep your laptop with you and send safely. The proposal goes out after a few minutes of setup.',defer:'You agree a delay and send from a suitable place after arrival. Your manager updates the customer; there is no hidden workaround.'},
payroll:{recover:"You report the action and time, not the password. Your work computer support team directs safe steps to regain access and checks whether to sign the account out on devices or apps where it is already signed in.",done:"Your staff/payroll team checks through its established route. Your report helps protect other staff without spreading the square scanning code."},
mfa:{recover:"Your work computer support team helps restore safe account access and signs the account out on devices or apps where it is already signed in when needed. Your report contains facts, not codes or backup sign-in secrets.",done:"You keep the approved sign-in protection and use approved steps to regain access if it becomes unavailable."},
supplier:{recover:"Authorised staff contact the bank urgently. You give transaction facts and make no further payment. Recovering the money is not guaranteed.",hold:"Payment stays with the person authorised to approve payment until established checking is possible. The team must explain the recorded delay.",backup:"The person authorised to approve payment uses the agreed backup route, checks the change and records approval. Payment proceeds without trusting the new number."},
ai:{done:'You use the approved manual route and raise the need for a safe tool. No customer records go to an unapproved service.'},
wrongrecipient:{done:"The approved team records the personal-data breach and the reasons for its decisions for the organisation deciding why and how the information is used, assesses risk and decides messages to people outside the organisation. You do not contact people or the UK data protection regulator yourself."},
converter:{recover:"You report what you ran and when, then follow instructions for disconnecting the device. The team responsible for handling the concern directs restoring safe work; do not reset or pay a demand to unlock files.",done:"Your work computer support team provides an approved converter. The work gets done without disabling protection or moving data to a personal device."},
lost:{done:"The team gets the facts and directs how to limit further harm. The colleague searches safely for the taxi."},
report:{done:"The team has the first report. Taylor follows instructions for safely regaining access. You thank them for reporting quickly."},
law:{done:"Your manager confirms the person responsible for handling the concern and reporting routes. Quick reporting supports decisions based on the likely harm to people; training is not formal approval."}};
function shortNode(event,node){const key=currentNode(event);return SHORT_NODES[event.id]?.[key]||node.text;}
const CLUES={
payroll:[['Sender','payroll-alerts@workplace-pay.invalid','The display name says Payroll Team. This address alone cannot prove who sent it. Compare with a known route, not the logo.'],["Where the square scanning code leads",'workplace-pay.invalid/verify',"This is not your known payroll bookmark. A square scanning code hides the destination until inspected; open the genuine website yourself."],['Urgency','Salary may be held. Act by 17:00.','Urgency can be legitimate, but is not permission to skip an independent check.']],
mfa:[["Did you start this sign-in?",'Did you try to sign in? No.',"Reject a sign-in request you did not start. If you already approved one, report it as soon as you can."],['Caller identity',"\"Work computer support\" knows your manager's name.","A name is not proof of identity. Use the known work computer support number, not one supplied by the caller."],['Requested action',"Approve a sign-in request or read out a code.",'Both can enable sign-in. Do not share codes or approve unexpected requests.']],
supplier:[['Conversation','An existing supplier conversation',"An existing account may be accessed or controlled without permission. A familiar conversation does not check new bank details."],['Voice',"\"Skip the call using an established phone number just this once.\"","A convincing voice can be imitated. Follow the established checking and approval process."],["Number supplied for checking",'A new number supplied in this request',"Calling the sender's own number is not checking through a separate, trusted contact. Use your established contact."]],
converter:[['Permissions',"Run with permission to change important device settings",'This gives software wider control. Ask for an approved tool, not a security workaround.'],['Protection',"Disable protection that checks for harmful software as you work",'Stop. A converter request is not permission to disable protection.'],['File destination','Upload a customer document',"A new service is a new place receiving work information. Check approval before sending work information."]]};
const REPORT_FACTS=[
{id:'time',label:'15:32: opened an unexpected email link',good:true},
{id:'password',label:'Entered a work-email password on a work laptop',good:true},
{id:'mfa',label:"No extra sign-in check was approved. No files were downloaded or run",good:true},
{id:'closed',label:'Closed the page; account access is unknown',good:true},
{id:'attacker',label:'An overseas attacker definitely stole all records',good:false},
{id:'secret',label:"Include the password so your work computer support team can test it",good:false}];
function activeWork(event,node,path){
 if(event.id==='workspace'&&!path.length&&!state.work?.setupChecked)return setupPanel();
 if(event.id==='report'&&(currentNode(event)==='facts'||node.end)&&!state.work?.reportBuilt){return `<section class="active-work" aria-label="Build the report"><h3>Put the facts in the report</h3><p>Use Taylor's message. Select four observed facts, not guesses or secrets.</p><form id="task-report"><fieldset id="report-facts" aria-describedby="task-report-feedback"><legend>Report facts</legend>${REPORT_FACTS.map(f=>`<label><input type="checkbox" name="fact" aria-describedby="task-report-feedback" value="${f.id}" ${reportDraft.includes(f.id)?'checked':''}> ${esc(f.label)}</label>`).join('')}</fieldset><label class="field" for="report-destination">Send through which route?</label><select id="report-destination" aria-describedby="task-report-feedback"><option value="" ${reportDestination===''?'selected':''}>Choose a route</option><option value="trusted" ${reportDestination==='trusted'?'selected':''}>Known reporting contact or backup</option><option value="broadcast" ${reportDestination==='broadcast'?'selected':''}>Everyone in the company</option><option value="sender" ${reportDestination==='sender'?'selected':''}>Reply to the suspicious email</option></select><p class="hint">Use the known backup if normal email may be accessed or controlled without permission. This is a practice selection; nothing is sent.</p><p id="task-report-feedback" class="error" role="alert"></p><button class="primary">Prepare report</button></form></section>`;}
 if(event.id==='report'&&state.work?.reportBuilt)return "<details class=\"prepared-report\"><summary>Your prepared report</summary><p>15:32: Taylor entered a work-email password after opening an unexpected email link on a work laptop. No extra sign-in check was approved. No files were downloaded or run. Page closed; account access unknown.</p><p>Raised through the known reporting contact or backup. No password included. This practice report was not sent.</p></details>";
 if(path.length||workStage[event.id])return '';
 if(CLUES[event.id]){const last=inspectState[event.id]?.at(-1),clue=CLUES[event.id][last];return `<section class="active-work"><h3>Inspect the request</h3><p>Inspect at least two details. A clue is a reason to check, not proof of fraud.</p><div class="clue-controls">${CLUES[event.id].map((c,i)=>`<button class="clue" data-inspect="${i}" aria-expanded="${last===i}" aria-controls="clue-detail">${esc(c[0])}${inspectState[event.id]?.includes(i)?' · inspected':''}</button>`).join('')}</div><div id="clue-detail" aria-live="polite">${clue?`<div class="feedback"><h4 aria-level="3">${esc(clue[0])}: ${esc(clue[1])}</h4><p>${esc(clue[2])}</p></div>`:''}</div><p class="hint">${inspectState[event.id]?.length||0} of 3 details inspected</p><button id="inspection-next" class="primary" ${(inspectState[event.id]?.length||0)<2?'disabled':''}>Choose your response</button></section>`;}
 if(event.id==='ai'&&state.work?.triage!=='routine')return `<section class="active-work"><h3>Move this request to its route</h3><p>Usual work screen, expected task, people allowed to receive it. No new link, sign-in, payment or permission change.</p><div class="choices">${[['routine','Normal work'],['verify',"Check first"],['urgent',"Report a security concern"]].map(c=>`<button data-inbox-route="${c[0]}">${c[1]}</button>`).join('')}</div><p id="inbox-feedback" role="status"></p></section>`;
 return '';
}
function workPending(event,path){if(event.id==='workspace'&&!path.length)return !state.work?.setupChecked;if(event.id==='report'&&currentNode(event)==='facts')return !state.work?.reportBuilt;if(path.length)return false;if(CLUES[event.id])return !workStage[event.id];if(event.id==='ai')return state.work?.triage!=='routine';return false;}
function workReady(event,path){if(event.id==='workspace'&&!path.length)return !!state.work?.setupChecked;if(event.id==='report'&&currentNode(event)==='facts')return !!state.work?.reportBuilt;if(path.length)return true;if(CLUES[event.id])return !!workStage[event.id];if(event.id==='ai')return state.work?.triage==='routine';return true;}
function bindWork(event){document.querySelectorAll('[data-setup]').forEach(c=>c.onchange=()=>{const count=document.querySelectorAll('[data-setup]:checked').length;document.getElementById('setup-count').textContent=count+' of 4 checked';document.getElementById('setup-next').disabled=count!==4;});const setupNext=document.getElementById('setup-next');if(setupNext)setupNext.onclick=()=>{state.work.setupChecked=true;save();day(event.id);focusDecision();say('Workspace checks complete. Choose your response.');};const path=state.paths[event.id]||[];const update=()=>{const ok=workReady(event,path);document.querySelectorAll('[data-choice]').forEach(b=>b.disabled=!ok);};update();
 document.querySelectorAll('[data-inspect]').forEach(b=>b.onclick=()=>{const i=Number(b.dataset.inspect);if(!inspectState[event.id])inspectState[event.id]=[];inspectState[event.id]=inspectState[event.id].filter(n=>n!==i);inspectState[event.id].push(i);state.work.inspections=inspectState;save();const c=CLUES[event.id][i];document.getElementById('clue-detail').innerHTML=`<div class="feedback"><h4 aria-level="3">${esc(c[0])}: ${esc(c[1])}</h4><p>${esc(c[2])}</p></div>`;b.textContent=c[0]+' · inspected';document.querySelectorAll('[data-inspect]').forEach(c=>c.setAttribute('aria-expanded',String(c===b)));document.querySelector('.active-work .hint').textContent=inspectState[event.id].length+' of 3 details inspected';document.getElementById('inspection-next').disabled=inspectState[event.id].length<2;update();});
 const inspectionNext=document.getElementById('inspection-next');if(inspectionNext)inspectionNext.onclick=()=>{workStage[event.id]=true;day(event.id);focusDecision();say('Request inspected. Choose your response.');};
 document.querySelectorAll('[data-inbox-route]').forEach(b=>b.onclick=()=>{if(b.dataset.inboxRoute!=='routine'){document.getElementById('inbox-feedback').textContent="This is expected work through the usual approved route. Reporting it as a security concern only because it arrived in chat adds work without a specific reason. Try the normal route; stay alert if the request changes.";return;}state.work.triage='routine';save();day(event.id);focusDecision();say("Moved to normal work. Now open the work screen.");});
 const form=document.getElementById('task-report');if(form){form.onchange=()=>{reportDraft=[...new FormData(form).getAll('fact')];reportDestination=document.getElementById('report-destination').value;document.getElementById('task-report-feedback').textContent='';document.getElementById('report-facts').removeAttribute('aria-invalid');document.getElementById('report-destination').removeAttribute('aria-invalid');};form.onsubmit=e=>{e.preventDefault();const facts=new FormData(form).getAll('fact');reportDraft=facts;reportDestination=document.getElementById('report-destination').value;const good=REPORT_FACTS.filter(f=>f.good).map(f=>f.id);const factsOK=facts.length===4&&good.every(id=>facts.includes(id)),routeOK=document.getElementById('report-destination').value==='trusted';if(!factsOK||!routeOK){const unsafe=REPORT_FACTS.filter(f=>!f.good&&facts.includes(f.id)),missing=REPORT_FACTS.filter(f=>f.good&&!facts.includes(f.id));const correctionNames={time:"time and unexpected link",password:"password entry and device",mfa:"sign-in approval and downloads",closed:"page closed and access unknown",attacker:"the unverified attacker claim",secret:"the password-sharing suggestion"};const corrections=[];if(unsafe.length)corrections.push("Leave out: "+unsafe.map(f=>correctionNames[f.id]).join("; ")+".");if(missing.length)corrections.push("Still needed: "+missing.map(f=>correctionNames[f.id]).join("; ")+".");if(!routeOK)corrections.push("Use the known reporting contact or backup, not a broad message or reply to the suspicious email.");document.getElementById('task-report-feedback').textContent=corrections.join(" ");document.getElementById('report-facts').setAttribute('aria-invalid',String(!factsOK));document.getElementById('report-destination').setAttribute('aria-invalid',String(!routeOK));if(!factsOK)form.querySelector(`input[value="${(unsafe[0]||missing[0]).id}"]`).focus();else document.getElementById('report-destination').focus();return;}state.work.reportBuilt=true;if(currentNode(event)==='facts'){const from='facts',choice=event.nodes.facts.choices[0];state.paths.report=[...path,{from,to:choice[1],label:choice[0]}];}if(event.nodes[currentNode(event)].end&&!state.done.includes('report'))state.done.push('report');save();day(event.id);focusDecision();say('Practice report prepared. Nothing was sent.');};}
}
const MODULE_SUMMARIES={
remote:{'Start with the approved setup':"Use the approved device and connection. Your organisation's approved private-network connection (VPN) protects a connection between your device and work systems, not every website.",'Protect what people can see and hear':'Choose a private enough place. Lock your screen and keep the device secure.','A deadline is not an exception':'Explain a block and ask for an approved route, rather than bypassing protection.'},
phishing:{'A convincing message can still be unsafe':'Judge the requested action, not the logo, timing or familiar name.','Use a route you already trust':'Open the genuine service yourself or use an established independent contact.','If you already clicked':"Report what you did as soon as you can. A click, entered password and download need different responses."},
accounts:{'One account, one password':'Use different passwords and an approved tool that stores and creates them. Never share a work sign-in.','An extra check when signing in':"Only approve sign-ins you started. Report accidental approvals as soon as you can.",'Use the approved way to regain access':"Use the known support route to regain access safely. Keep passwords and codes private."},
social:{'People and authority can be imitated':"A familiar account, voice or job title does not prove the identity of a new request.",'Protect the process':'Keep established payment checks and approvals, even under deadline pressure.','A safe refusal can be simple':"Explain that you need to follow the process. Offer an approved route or ask for help with what is blocked."},
data:{'Check purpose, person and permission':'Check the recipient and permission, then share only what the task needs.','Tools also receive your information':"Check approval before using a new automatic writing tool, file-sharing site or file conversion service.",'A security problem is more than theft':"A wrong recipient or lost device may expose personal information. Report as soon as you can."},
devices:{'Managed settings have a purpose':'Use approved software and updates. Do not disable protection to get a task done.','Protect the physical device':'Lock, secure and keep track of your work device, especially while travelling.','Report the problem, do not experiment':"After unexpected changes, stop experimenting and use the agreed reporting route."},
incidents:{'You do not need proof':"Report a concern as soon as you can, even if unsure or embarrassed. Use the known contact or backup.",'Stop further harm without destroying evidence':'Follow the plan for handling security concerns. Do not erase evidence, reset devices or spread suspicious material.','A short factual report is enough to start':"Give the time, device or service, observed actions and what is unknown. Leave secrets out."}
};
const SETUP_CHECKS=[['device','Approved work laptop','Use your approved device, not a shared station computer.'],['connection','Approved connection',"Use the organisation-approved connection and access method. A request to change settings on a page asking you to join a network is not approval from your work computer support team."],['privacy','Private enough space','Check who can see the screen or hear a confidential call.'],['help','Known contact or backup','Have an approved support route if a safe setup is unavailable.']];
function setupPanel(){return `<section class="active-work"><h3>Prepare your workspace</h3><p>Check four things before handling the proposal. Open each item, then mark it checked.</p>${SETUP_CHECKS.map(c=>`<details><summary>${esc(c[1])}</summary><p>${esc(c[2])}</p><label><input type="checkbox" data-setup="${c[0]}"> Checked in this practice setup</label></details>`).join('')}<p class="hint" id="setup-count">0 of 4 checked</p><button class="primary" id="setup-next" disabled>Use this setup</button></section>`;}

// Optional contrast cases: changed facts can change the next action.
const CHANGE_CASES=[
{id:'update-change',title:'An update request changes',first:'Your managed work laptop offers an update through the normal organisation update process. No unusual permission or conflicting warning.',firstAnswer:0,firstWhy:"Use the approved update process. Ordinary approved work does not need to be reported as a security concern only because it is online.",changed:"Now a browser pop-up asks you to install new settings that change how the device connects or is managed from an unfamiliar website. You have not installed it.",changedAnswer:1,changedWhy:"The website and requested access changed. Stop this pop-up and use the known work computer support team route or approved update process. Do not install those settings."},
{id:'payment-change',title:'A supplier change becomes a payment',first:"An existing supplier conversation requests new bank details and provides a new phone number to check them. You have not paid.",firstAnswer:1,firstWhy:"Use the established supplier contact and required approvals. Use a trusted contact you already have, not a number supplied by this request.",changed:'A colleague now says the payment has already been sent to those new details without the established check.',changedAnswer:2,changedWhy:"Report urgently through the known reporting or payment concern route. Authorised staff may need to contact the bank. Do not send another payment; recovering the money is not guaranteed."},
{id:'signin-change',title:"An unfamiliar link leads to possible account access",first:'A chat account says your project files moved to a new service and asks you to sign in. You did not expect a move and have not opened it.',firstAnswer:1,firstWhy:"Check through the usual project service or established independent contact, not the supplied link. A familiar account can be accessed or controlled without permission.",changed:"You now learn a colleague entered their work password through that link and approved an unexpected sign-in request.",changedAnswer:2,changedWhy:"Report the actions and time as soon as you can through a trusted route. The team responsible for handling the concern directs restoring safe account access and signing the account out on devices or apps where it is already signed in. Never include the password or codes."},
{id:'audience-change',title:"A routine update changes who receives it",first:"Your manager requests the normal three-point summary from the approved work screen for the usual approved internal team.",firstAnswer:0,firstWhy:"Use the normal approved work screen and group of people. Stay alert if the task changes.",changed:"The next message asks you to upload the customer spreadsheet to a new free website that generates text or summaries automatically to make the summary. Approval for that tool or sharing information is not known.",changedAnswer:1,changedWhy:"A new tool receives the work information. Check approval for the tool and information first, or use the approved manual route. A routine request did not authorise this change."}
];
let changeIndex=0,changeStage=0,changeAnswer=null;
function changePanel(){const c=CHANGE_CASES[changeIndex],changed=changeStage===1,right=changeAnswer===(changed?c.changedAnswer:c.firstAnswer);return `<details class="rule" id="change-practice"><summary>Practise when the facts change</summary><div id="change-card"><p class="eyebrow">Case ${changeIndex+1} of ${CHANGE_CASES.length} · ${changed?'Changed facts':'First request'}</p><h2 id="change-title" tabindex="-1">${esc(c.title)}</h2><p>${esc(changed?c.changed:c.first)}</p>${changed?`<details class="change-compare"><summary>Compare with the first request</summary><p>${esc(c.first)}</p><p class="hint">What changed? Does that change the route you should use?</p></details>`:''}<div class="choices" role="group" aria-label="Choose the route for these facts">${TRIAGE_LABELS.map((label,i)=>`<button class="choice" data-change-answer="${i}" aria-pressed="${changeAnswer===i}">${esc(label)}</button>`).join('')}</div><div id="change-feedback" role="status">${changeAnswer!==null?`<div class="feedback ${right?'':'wrong'}"><strong>${right?'Useful next step.':'Review these facts.'}</strong> ${esc(changed?c.changedWhy:c.firstWhy)}${right?'':' Try another route.'}</div>`:''}</div><div class="actions">${right?`<button id="change-next" class="primary">${!changed?'See what changes':changeIndex<CHANGE_CASES.length-1?'Next case':'Start these cases again'}</button>`:''}</div><p class="hint">Unscored teaching cases. Your local procedure may ask you to report any concern before possible access without permission. This exercise does not send anything or change course completion.</p></div></details>`;}
function bindChange(){const host=document.getElementById('change-practice');if(!host)return;const update=()=>{const compareOpen=host.querySelector('.change-compare')?.open===true;host.outerHTML=changePanel();document.getElementById('change-practice').open=true;const comparison=document.querySelector('.change-compare');if(comparison)comparison.open=compareOpen;bindChange();};document.querySelectorAll('[data-change-answer]').forEach(button=>button.onclick=()=>{changeAnswer=Number(button.dataset.changeAnswer);update();const replacement=document.querySelector(`[data-change-answer="${changeAnswer}"]`);replacement.focus({preventScroll:true});const c=CHANGE_CASES[changeIndex];say((changeAnswer===(changeStage?c.changedAnswer:c.firstAnswer)?'Useful next step. ':'Review these facts. ')+(changeStage?c.changedWhy:c.firstWhy));});const next=document.getElementById('change-next');if(next)next.onclick=()=>{if(changeStage===0)changeStage=1;else{changeStage=0;changeIndex=(changeIndex+1)%CHANGE_CASES.length;}changeAnswer=null;update();document.getElementById('change-title').focus();};}
