'use strict';
// All cards are local teaching props. There are no external actions.
const SHORT_INTROS={
workspace:'Your train is delayed. A confidential proposal is due at 09:00. The station Wi-Fi wants you to install a security profile.',
payroll:'You expected a payslip this week. This email says your salary could be delayed.',
mfa:'Three sign-in prompts arrive. You did not start them. Then this caller contacts you.',
supplier:'A familiar supplier thread asks for new bank details. A voice note sounds like your manager.',
ai:'Jamie asks for the usual update. Open the desk card below and put it on the right route.',
wrongrecipient:'You notice a staff-pay spreadsheet went to the wrong external recipient one minute ago.',
converter:'You need to convert a work document. This page wants you to change device settings.',
lost:'A colleague may have left a work laptop in a taxi. It might turn up tomorrow.',
report:'Taylor wants help reporting a mistake. Build a useful report from the clues, without blame.',
law:'A customer file went outside the business. Your manager wants to leave it until Monday.'};
const SHORT_NODES={
workspace:{private:'You check the booth, keep your laptop with you and send safely. The proposal goes out after a few minutes of setup.',defer:'You agree a delay and send from a suitable place after arrival. Your manager updates the customer; there is no hidden workaround.'},
payroll:{recover:'You report the action and time, not the password. IT directs genuine recovery and checks whether active sessions need revoking.',done:'HR checks through its established route. Your report helps protect other staff without spreading the QR code.'},
mfa:{recover:'IT directs account recovery and any session action. Your report contains facts, not codes or recovery secrets.',done:'You keep the approved sign-in protection and use official recovery if it becomes unavailable.'},
supplier:{recover:'Authorised staff contact the bank urgently. You give transaction facts and make no further payment. Recovery is not guaranteed.',hold:'Payment stays with the approver until established verification is possible. The team must explain the recorded delay.',backup:'The approver uses the agreed backup route, verifies the change and records approval. Payment proceeds without trusting the new number.'},
ai:{done:'You use the approved manual route and raise the need for a safe tool. No customer records go to an unapproved service.'},
wrongrecipient:{done:'The authorised team records the breach, assesses risk and decides external notices. You do not contact people or the ICO yourself.'},
converter:{recover:'You report what you ran and when, then follow isolation instructions. The response team directs recovery; do not reset or pay a ransom.',done:'IT provides an approved converter. The work gets done without disabling protection or moving data to a personal device.'},
lost:{done:'The team gets the facts and directs containment. The colleague searches safely for the taxi.'},
report:{done:'The team has the first report. Taylor follows genuine recovery instructions. You thank them for reporting promptly.'},
law:{done:'Your manager confirms the response owner and reporting routes. Prompt reporting supports risk-based decisions; training is not certification.'}};
function shortNode(event,node){const key=currentNode(event);return SHORT_NODES[event.id]?.[key]||node.text;}
const CLUES={
payroll:[['Sender','payroll-alerts@workplace-pay.invalid','The display name says Payroll Team. This address alone cannot prove who sent it. Compare with a known route, not the logo.'],['QR destination','workplace-pay.invalid/verify','This is not your known payroll bookmark. A QR code hides the destination until inspected; open the genuine portal yourself.'],['Urgency','Salary may be held. Act by 17:00.','Urgency can be legitimate, but is not permission to skip an independent check.']],
mfa:[['Sign-in context','Did you try to sign in? No.','Reject a prompt you did not start. If you already approved one, report it promptly.'],['Caller identity','"IT Support" knows your manager\'s name.','A name is not authentication. Use the known helpdesk number, not one supplied by the caller.'],['Requested action','Approve a prompt or read out a code.','Both can enable sign-in. Do not share codes or approve unexpected requests.']],
supplier:[['Thread','An existing supplier conversation','An existing account may be compromised. A familiar thread does not verify new bank details.'],['Voice','"Skip the call-back just this once."','A convincing voice can be imitated. Follow the established verification and approval process.'],['Callback number','A new number supplied in this request','Calling the sender\'s own number is not independent verification. Use your established contact.']],
converter:[['Permissions','Run as administrator','This gives software wider control. Ask for an approved tool, not a security workaround.'],['Protection','Disable real-time protection','Stop. A converter request is not permission to disable protection.'],['File destination','Upload a customer document','A new service is a new data destination. Check approval before sending work information.']]};
const REPORT_FACTS=[
{id:'time',label:'15:32: opened an unexpected email link',good:true},
{id:'password',label:'Entered a work-email password on a work laptop',good:true},
{id:'mfa',label:'No MFA approval, download or file execution',good:true},
{id:'closed',label:'Closed the page; account access is unknown',good:true},
{id:'attacker',label:'An overseas attacker definitely stole all records',good:false},
{id:'secret',label:'Include the password so IT can test it',good:false}];
function activeWork(event,node,path){
 if(event.id==='workspace'&&!path.length&&!state.work?.setupChecked)return setupPanel();
 if(event.id==='report'&&(currentNode(event)==='facts'||node.end)&&!state.work?.reportBuilt){return `<section class="active-work" aria-label="Build the report"><h3>Put the facts in the report</h3><p>Use Taylor's message. Select four observed facts, not guesses or secrets.</p><form id="task-report"><fieldset id="report-facts" aria-describedby="task-report-feedback"><legend>Report facts</legend>${REPORT_FACTS.map(f=>`<label><input type="checkbox" name="fact" value="${f.id}" ${reportDraft.includes(f.id)?'checked':''}> ${esc(f.label)}</label>`).join('')}</fieldset><label class="field" for="report-destination">Send through which route?</label><select id="report-destination" aria-describedby="task-report-feedback"><option value="">Choose a route</option><option value="trusted">Known incident contact or backup</option><option value="broadcast">Everyone in the company</option><option value="sender">Reply to the suspicious email</option></select><p class="hint">Use the known backup if normal email may be compromised. This is a practice selection; nothing is sent.</p><p id="task-report-feedback" class="error" role="alert"></p><button class="primary">Prepare report</button></form></section>`;}
 if(event.id==='report'&&state.work?.reportBuilt)return '<details class="prepared-report"><summary>Your prepared report</summary><p>15:32: Taylor entered a work-email password after opening an unexpected email link on a work laptop. No MFA approval, downloads or file execution. Page closed; account access unknown.</p><p>Raised through the known incident contact or backup. No password included. This practice report was not sent.</p></details>';
 if(path.length||workStage[event.id])return '';
 if(CLUES[event.id])return `<section class="active-work"><h3>Inspect the request</h3><p>Open at least two details before deciding. A clue calls for checking; it is not proof of fraud.</p><div class="clue-controls">${CLUES[event.id].map((c,i)=>`<button class="clue" data-inspect="${i}" aria-expanded="false" aria-controls="clue-detail">${esc(c[0])}${inspectState[event.id]?.includes(i)?' · inspected':''}</button>`).join('')}</div><div id="clue-detail" aria-live="polite"></div><p class="hint">${inspectState[event.id]?.length||0} of 3 details inspected</p><button id="inspection-next" class="primary" ${(inspectState[event.id]?.length||0)<2?'disabled':''}>Choose your response</button></section>`;
 if(event.id==='ai'&&state.work?.triage!=='routine')return `<section class="active-work"><h3>Move this request to its route</h3><p>Usual dashboard, expected task, authorised audience. No new link, sign-in, payment or permission change.</p><div class="choices">${[['routine','Normal work'],['verify','Verify first'],['urgent','Incident reporting']].map(c=>`<button data-inbox-route="${c[0]}">${c[1]}</button>`).join('')}</div><p id="inbox-feedback" role="status"></p></section>`;
 return '';
}
function workPending(event,path){if(event.id==='workspace'&&!path.length)return !state.work?.setupChecked;if(event.id==='report'&&currentNode(event)==='facts')return !state.work?.reportBuilt;if(path.length)return false;if(CLUES[event.id])return !workStage[event.id];if(event.id==='ai')return state.work?.triage!=='routine';return false;}
function workReady(event,path){if(event.id==='workspace'&&!path.length)return !!state.work?.setupChecked;if(event.id==='report'&&currentNode(event)==='facts')return !!state.work?.reportBuilt;if(path.length)return true;if(CLUES[event.id])return !!workStage[event.id];if(event.id==='ai')return state.work?.triage==='routine';return true;}
function bindWork(event){document.querySelectorAll('[data-setup]').forEach(c=>c.onchange=()=>{const count=document.querySelectorAll('[data-setup]:checked').length;document.getElementById('setup-count').textContent=count+' of 4 checked';document.getElementById('setup-next').disabled=count!==4;});const setupNext=document.getElementById('setup-next');if(setupNext)setupNext.onclick=()=>{state.work.setupChecked=true;save();day(event.id);focusDecision();say('Workspace checks complete. Choose your response.');};const path=state.paths[event.id]||[];const update=()=>{const ok=workReady(event,path);document.querySelectorAll('[data-choice]').forEach(b=>b.disabled=!ok);};update();
 document.querySelectorAll('[data-inspect]').forEach(b=>b.onclick=()=>{const i=Number(b.dataset.inspect);if(!inspectState[event.id])inspectState[event.id]=[];if(!inspectState[event.id].includes(i))inspectState[event.id].push(i);state.work.inspections=inspectState;save();const c=CLUES[event.id][i];document.getElementById('clue-detail').innerHTML=`<div class="feedback"><h4>${esc(c[0])}: ${esc(c[1])}</h4><p>${esc(c[2])}</p></div>`;b.textContent=c[0]+' · inspected';document.querySelectorAll('[data-inspect]').forEach(c=>c.setAttribute('aria-expanded',String(c===b)));document.querySelector('.active-work .hint').textContent=inspectState[event.id].length+' of 3 details inspected';document.getElementById('inspection-next').disabled=inspectState[event.id].length<2;update();});
 const inspectionNext=document.getElementById('inspection-next');if(inspectionNext)inspectionNext.onclick=()=>{workStage[event.id]=true;day(event.id);focusDecision();say('Request inspected. Choose your response.');};
 document.querySelectorAll('[data-inbox-route]').forEach(b=>b.onclick=()=>{if(b.dataset.inboxRoute!=='routine'){document.getElementById('inbox-feedback').textContent='This is expected work through an established route. Extra escalation adds work without resolving a specific concern. Try the normal route; stay alert if the request changes.';return;}state.work.triage='routine';save();day(event.id);focusDecision();say('Moved to normal work. Now open the dashboard.');});
 const form=document.getElementById('task-report');if(form){form.onchange=()=>{reportDraft=[...new FormData(form).getAll('fact')];document.getElementById('task-report-feedback').textContent='';document.getElementById('report-facts').removeAttribute('aria-invalid');document.getElementById('report-destination').removeAttribute('aria-invalid');};form.onsubmit=e=>{e.preventDefault();const facts=new FormData(form).getAll('fact');reportDraft=facts;const good=REPORT_FACTS.filter(f=>f.good).map(f=>f.id);const factsOK=facts.length===4&&good.every(id=>facts.includes(id)),routeOK=document.getElementById('report-destination').value==='trusted';if(!factsOK||!routeOK){document.getElementById('task-report-feedback').textContent=!factsOK?'Choose all four observed facts. Leave guesses and passwords out.':'Use the known incident contact or backup, not a broad message or reply to the suspicious email.';document.getElementById('report-facts').setAttribute('aria-invalid',String(!factsOK));document.getElementById('report-destination').setAttribute('aria-invalid',String(!routeOK));if(!factsOK)form.querySelector('input').focus();else document.getElementById('report-destination').focus();return;}state.work.reportBuilt=true;if(currentNode(event)==='facts'){const from='facts',choice=event.nodes.facts.choices[0];state.paths.report=[...path,{from,to:choice[1],label:choice[0]}];}if(event.nodes[currentNode(event)].end&&!state.done.includes('report'))state.done.push('report');save();day(event.id);focusDecision();say('Practice report prepared. Nothing was sent.');};}
}
const MODULE_SUMMARIES={
remote:{'Start with the approved setup':'Use the approved device and connection. A VPN protects a connection path, not every website.','Protect what people can see and hear':'Choose a private enough place. Lock your screen and keep the device secure.','A deadline is not an exception':'Explain a block and ask for an approved route, rather than bypassing protection.'},
phishing:{'A convincing message can still be unsafe':'Judge the requested action, not the logo, timing or familiar name.','Use a route you already trust':'Open the genuine service yourself or use an established independent contact.','If you already clicked':'Report what you did promptly. A click, entered password and download need different responses.'},
accounts:{'One account, one password':'Use unique passwords and an approved password manager. Never share a work sign-in.','MFA is an extra check':'Only approve sign-ins you started. Report accidental approvals promptly.','Use the official recovery process':'Use genuine recovery through the known IT route. Keep passwords and codes private.'},
social:{'People and authority can be imitated':'A familiar account, voice or job title does not authenticate a new request.','Protect the process':'Keep established payment checks and approvals, even under deadline pressure.','A safe refusal can be simple':'Explain that you need to follow the process. Offer an approved route or raise the block.'},
data:{'Check purpose, person and permission':'Check the recipient and permission, then share only what the task needs.','Tools also receive your data':'Check approval before using a new AI, file-sharing or conversion service.','A breach is more than theft':'A wrong recipient or lost device may expose personal information. Report promptly.'},
devices:{'Managed settings have a purpose':'Use approved software and updates. Do not disable protection to get a task done.','Protect the physical device':'Lock, secure and keep track of your work device, especially while travelling.','Respond, do not improvise':'After unexpected changes, stop experimenting and use the agreed response route.'},
incidents:{'You do not need proof':'Report a concern promptly, even if unsure or embarrassed. Use the known contact or backup.','Stop further harm without destroying evidence':'Follow the response plan. Do not erase evidence, reset devices or spread suspicious material.','A short factual report is enough to start':'Give the time, device/service, observed actions and what is unknown. Leave secrets out.'}
};
const SETUP_CHECKS=[['device','Approved work laptop','Use your approved device, not a shared station computer.'],['connection','Approved connection','Use the organisation-approved connection and access method. A portal profile is not IT approval.'],['privacy','Private enough space','Check who can see the screen or hear a confidential call.'],['help','Known contact or backup','Have an approved support route if a safe setup is unavailable.']];
function setupPanel(){return `<section class="active-work"><h3>Prepare your workspace</h3><p>Check four things before handling the proposal. Open each item, then mark it checked.</p>${SETUP_CHECKS.map(c=>`<details><summary>${esc(c[1])}</summary><p>${esc(c[2])}</p><label><input type="checkbox" data-setup="${c[0]}"> Checked in this practice setup</label></details>`).join('')}<p class="hint" id="setup-count">0 of 4 checked</p><button class="primary" id="setup-next" disabled>Use this setup</button></section>`;}

// Optional contrast cases: changed facts can change the next action.
const CHANGE_CASES=[
{id:'update-change',title:'An update request changes',first:'Your managed work laptop offers an update through the normal organisation update process. No unusual permission or conflicting warning.',firstAnswer:0,firstWhy:'Use the approved update process. Ordinary approved work does not need an escalation just because it is online.',changed:'Now a browser pop-up says the update needs a new security profile from an unfamiliar website. You have not installed it.',changedAnswer:1,changedWhy:'The route and permissions changed. Stop this pop-up and use the known IT route or approved update process. Do not install the profile.'},
{id:'payment-change',title:'A supplier change becomes a payment',first:'An existing supplier thread requests new bank details and provides a new phone number to verify them. You have not paid.',firstAnswer:1,firstWhy:'Use the established supplier contact and required approvals. The request must not supply its own independent verification.',changed:'A colleague now says the payment has already been sent to those new details without the established check.',changedAnswer:2,changedWhy:'Report urgently through the known response/payment route. Authorised staff may need to contact the bank. Do not send another payment; recovery is not guaranteed.'},
{id:'signin-change',title:'An unfamiliar link becomes an exposure',first:'A chat account says your project files moved to a new service and asks you to sign in. You did not expect a move and have not opened it.',firstAnswer:1,firstWhy:'Verify through the usual project service or established independent contact, not the supplied link. A familiar account can be compromised.',changed:'You now learn a colleague entered their work password through that link and approved an unexpected sign-in prompt.',changedAnswer:2,changedWhy:'Report the actions and time promptly through a trusted route. The response team directs recovery and any session action. Never include the password or codes.'},
{id:'audience-change',title:'A routine update changes audience',first:'Your manager requests the normal three-point summary from the approved dashboard for the usual authorised internal team.',firstAnswer:0,firstWhy:'Use the normal approved dashboard and audience. Stay alert if the task changes.',changed:'The next message asks you to upload the customer spreadsheet to a new free AI website to make the summary. Approval for that tool or disclosure is not known.',changedAnswer:1,changedWhy:'A new tool is a new data destination. Check tool and disclosure approval first, or use the approved manual route. A routine request did not authorise this change.'}
];
let changeIndex=0,changeStage=0,changeAnswer=null;
function changePanel(){const c=CHANGE_CASES[changeIndex],changed=changeStage===1,right=changeAnswer===(changed?c.changedAnswer:c.firstAnswer);return `<details class="rule" id="change-practice"><summary>Practise when the facts change</summary><div id="change-card"><p class="eyebrow">Case ${changeIndex+1} of ${CHANGE_CASES.length} · ${changed?'Changed facts':'First request'}</p><h2 id="change-title" tabindex="-1">${esc(c.title)}</h2><p>${esc(changed?c.changed:c.first)}</p><div class="choices" role="group" aria-label="Choose the route for these facts">${TRIAGE_LABELS.map((label,i)=>`<button class="choice" data-change-answer="${i}">${esc(label)}</button>`).join('')}</div><div id="change-feedback" role="status">${changeAnswer!==null?`<div class="feedback ${right?'':'wrong'}"><strong>${right?'Useful next step.':'Review these facts.'}</strong> ${esc(changed?c.changedWhy:c.firstWhy)}${right?'':' Try another route.'}</div>`:''}</div><div class="actions">${right?`<button id="change-next" class="primary">${!changed?'See what changes':changeIndex<CHANGE_CASES.length-1?'Next case':'Start these cases again'}</button>`:''}</div><p class="hint">Unscored teaching cases. Your local procedure may ask you to report any concern before exposure. This exercise does not send anything or change course completion.</p></div></details>`;}
function bindChange(){const host=document.getElementById('change-practice');if(!host)return;const update=()=>{host.outerHTML=changePanel();document.getElementById('change-practice').open=true;bindChange();};document.querySelectorAll('[data-change-answer]').forEach(button=>button.onclick=()=>{changeAnswer=Number(button.dataset.changeAnswer);update();const replacement=document.querySelector(`[data-change-answer="${changeAnswer}"]`);replacement.focus({preventScroll:true});const c=CHANGE_CASES[changeIndex];say((changeAnswer===(changeStage?c.changedAnswer:c.firstAnswer)?'Useful next step. ':'Review these facts. ')+(changeStage?c.changedWhy:c.firstWhy));});const next=document.getElementById('change-next');if(next)next.onclick=()=>{if(changeStage===0)changeStage=1;else{changeStage=0;changeIndex=(changeIndex+1)%CHANGE_CASES.length;}changeAnswer=null;update();document.getElementById('change-title').focus();};}
