const META={version:'1.0.9',checked:'6 October 2026',publisher:'Published by William Baptist | Tidy Desk Digital'};
const SOURCES=[
['S1','NCSC: Top Tips for Staff','https://www.ncsc.gov.uk/information/top-tips-for-staff','Staff training scope; training complements technical protection.'],
['S2','NCSC: Phishing attacks','https://www.ncsc.gov.uk/guidance/phishing','Independent verification, layered defences and supportive reporting.'],
['S3','NCSC: Secure your important online accounts','https://www.ncsc.gov.uk/collection/small-organisations-guide-to-cyber-security/secure-your-important-online-accounts','Unique passwords, password managers, MFA and passkeys.'],
['S4','NCSC: Why MFA matters','https://www.ncsc.gov.uk/collection/mfa-for-your-corporate-online-services/why-mfa-matters','Benefits and limits of MFA.'],
['S5','NCSC: Advice for End Users','https://www.ncsc.gov.uk/guidance/end-user-devices-advice-end-users','Managed devices, travel, physical security and loss reporting.'],
['S6','NCSC: Response and recovery','https://www.ncsc.gov.uk/collection/small-business-guidance--response-and-recovery','Preparing for and responding to incidents.'],
['S7','ICO: Personal data breaches','https://ico.org.uk/for-organisations/report-a-breach/personal-data-breach/personal-data-breaches-a-guide/','Breach definition, risk thresholds, recording and notification.'],
['S8','ICO: The first 72 hours','https://ico.org.uk/for-organisations/advice-for-small-organisations/personal-data-breaches/72-hours-how-to-respond-to-a-personal-data-breach/','Containment, investigation and risk assessment.'],
['S9','NCSC: Cyber Essentials','https://www.ncsc.gov.uk/cyberessentials/overview','Certification context; staff training is not certification.'],
['S10','ICO: Data (Use and Access) Act 2025','https://ico.org.uk/about-the-ico/what-we-do/legislation-we-cover/data-use-and-access-act-2025/','Current data protection reform context.'],
['S12','NCSC: QR codes and their risks','https://www.ncsc.gov.uk/blog-post/qr-codes-whats-real-risk','QR phishing context and proportionate caution.'],
['S13','US FTC: Public Wi-Fi safety','https://consumer.ftc.gov/articles/are-public-wi-fi-networks-safe-what-you-need-know','Encrypted connections do not prove a website is trustworthy.'],
['S15','NCSC: Virtual Private Networks','https://www.ncsc.gov.uk/collection/device-security-guidance/infrastructure/virtual-private-networks','Organisational VPN purpose; need depends on architecture and policy.'],
['S14','Swiss NCSC: Deepfake CEO fraud','https://www.ncsc.admin.ch/ncsc/en/home/aktuell/im-fokus/2024/wochenrueckblick_14.html','Voice/video impersonation and independent payment verification; not UK law.'],
['S11','UK Parliament: Cyber Security and Resilience (Network and Information Systems) Bill','https://bills.parliament.uk/bills/4035','Bill status only; not treated as an enacted universal staff duty.']
];
const MODULES=[
{id:'remote',title:'Your workspace is part of security',minutes:5,sources:['S5','S2','S13','S15'],goal:'Choose an approved connection and a suitable place for work.',sections:[
['Start with the approved setup','Use the approved device, connection and remote access method. Public network names can be copied. Use a corporate VPN when policy requires it, but do not assume it makes every site safe. A VPN does not make a phishing page or harmful download trustworthy.',['Do not bypass certificate warnings.','Do not install a security profile offered by an unexpected network portal.','Ask IT for an approved alternative if the normal route is unavailable.']],
['Protect what people can see and hear','A secure connection does not prevent someone reading your screen or hearing a customer call. Choose a space appropriate to the information. Lock the screen whenever you step away.',['Keep devices with you or secured; do not leave them unattended in public.','Do not lend a signed-in work session to someone else.','Check the organisation\'s travel approval rules before working overseas.']],
['A deadline is not an exception','If work cannot be done safely, explain what is blocked and ask for an approved route. Personal email, unapproved devices and disabled protection can turn a small delay into an incident.',['Know an urgent and out-of-hours reporting route.','Use approved storage so work is not held only on a laptop.','Prioritise personal safety if equipment is stolen.']]
],takeaway:'Approved device. Approved connection. Appropriate surroundings.'},
{id:'phishing',title:'Read the request, not the polish',minutes:6,sources:['S1','S2','S12','S13'],goal:'Verify a message without using the route supplied by the message.',sections:[
['A convincing message can still be unsafe','Phishing tries to make you disclose information, approve access, install software or send money. It can arrive by email, chat, text, phone or QR code. Good spelling, familiar names and expected timing do not prove a request is genuine. A real account may also be compromised.',['Pause at urgency, secrecy or changes to a normal process.','A QR code is another route to a destination, not proof of trust.','You do not need certainty before asking for help.']],
['Use a route you already trust','Open the service using your usual bookmark or app. Contact the person using a directory number or an established conversation, not details supplied by the suspicious request. A padlock means the connection is encrypted; it does not prove the business or request is honest.',['Do not open an attachment just to investigate it.','For payment changes, follow the verification and approval process.','Use the approved report-phishing tool; avoid spreading attachments.']],
['If you already clicked','Stop interacting and report promptly. Explain whether you opened the page, entered a password, approved MFA, downloaded a file or ran it. A click does not always mean compromise, but the response team needs the facts.',['Never include passwords or codes in a report.','Use a known alternative route if your normal account may be compromised.','Training is one layer; nobody can spot every attack.']]
],takeaway:'Unexpected action? Pause, verify independently, report concerns.'},
{id:'accounts',title:'Protect how you sign in',minutes:5,sources:['S3','S4','S5'],goal:'Reject unexpected access requests and keep sign-in secrets private.',sections:[
['One account, one password','Use strong, unique passwords. An approved password manager can generate and store them. Protect it with a strong unique password and MFA where available. For passwords you must remember, a long phrase made from unrelated words can help; follow local length requirements.',['Do not base passwords on public details about you.','Do not install a personal password tool for work without approval.','Never share a password with a manager, colleague or caller.']],
['MFA is an extra check','MFA adds protection beyond a password. Some methods can still be phished or abused. Approve only a sign-in you started, for the intended service. Where supported and approved, passkeys or security keys offer phishing-resistant sign-in.',['Reject and report unexpected approval prompts.','Do not read out a one-time code to a caller.','Repeated prompts are not something to clear by approving one.']],
['Use the official recovery process','A lost phone or locked account is a support problem, not a reason to share accounts. Store recovery codes using the approved secure method. Report suspected password disclosure and change it through the genuine service or IT route promptly.',['IT may also need to revoke active sessions.','Do not paste recovery codes into chat or a shared document.','Ask for a supported alternative if you cannot use the normal method.']]
],takeaway:'Unique passwords. Approved tools. Only approve sign-ins you started.'},
{id:'social',title:'Pressure does not replace permission',minutes:6,sources:['S2','S5','S14'],goal:'Handle impersonation and payment requests without bypassing checks.',sections:[
['People and authority can be imitated','An attacker may claim to be a director, supplier or IT technician. Names, job roles and project details can be public or stolen. Voice and video can be manipulated too. A convincing person is not the same as an authorised request.',['Urgency and secrecy are reasons to pause.','Use a known independent route to verify.','A senior person\'s apparent request does not remove controls.']],
['Protect the process','Verify new bank details through the established supplier process and required approvals. Do not install remote-control software or disclose secrets because a caller claims to be helping. A smaller test payment is still a payment, not a safe substitute for checks.',['Do not use the new phone number supplied in the payment email.','Do not buy gift cards to satisfy an unverified urgent request.','Escalate exceptions through the authorised approval route.']],
['A safe refusal can be simple','Say: "I need to verify this through our normal process." For unfamiliar visitors, use reception or the authorised contact. Do not lend badges or permit access simply because a visitor carries equipment.',['Be polite; do not put yourself at physical risk.','If money has already moved, report urgently so authorised staff can contact the bank.','Do not send another payment to try to reverse the first.']]
],takeaway:'Verify the change. Keep the approval process. Escalate pressure.'},
{id:'data',title:'New tool, new destination',minutes:6,sources:['S5','S7','S8'],goal:'Check recipients, contents and access before sharing.',sections:[
['Check purpose, person and permission','Before sharing, ask what is needed, who is authorised and which route is approved. Check the full recipient address, attachment contents and link permissions. A correct email can still contain the wrong file.',['Share the minimum information needed.','Do not make a restricted link public just to fix access.','Autocomplete and display names can hide mistakes.']],
['Tools also receive your data','Personal email, AI assistants, translation sites and online converters are new destinations. Familiar or free does not mean approved. Removing names may not make data anonymous if other details still identify someone.',['Keep work data out of unapproved tools.','Never put credentials or recovery codes into prompts or documents.','Follow retention, backup and secure disposal policies.']],
['A breach is more than theft','A personal data breach can affect confidentiality, integrity or availability. Wrong recipients, loss, corruption and loss of access with a significant negative effect on people can all matter. Report a suspected breach promptly.',['A recall request is not proof that an email was retrieved.','A deletion promise is useful evidence, not an automatic all-clear.','Let the response team assess risk; avoid broad forwarding.']]
],takeaway:'Check the recipient, contents and access before you send.'},
{id:'devices',title:'Keep protections in place',minutes:5,sources:['S1','S5','S9'],goal:'Use approved software and report loss or unusual behaviour.',sections:[
['Managed settings have a purpose','Do not disable protection to finish a task. Use approved installation routes. Allow required security updates through the managed process and report repeated failures. Search results and pop-ups are not IT approval.',['Do not use administrator access for routine work unless authorised.','Ask for an approved solution when a tool is blocked.','Different controls protect against different risks.']],
['Protect the physical device','Lock the screen when stepping away. Keep devices and media secure. Do not connect found USB sticks or unapproved peripherals to discover their owner. Use the agreed lost-media process.',['Use trusted approved chargers and cables.','Avoid leaving equipment visible in vehicles.','Do not lend signed-in devices.']],
['Respond, do not improvise','Report loss immediately, even if you hope to find the device. Unexpected encryption messages or changed files need urgent help. Poor performance alone is not proof of malware, but persistent problems deserve support.',['Do not install a clean-up tool, pay a ransom or use an outside repair shop yourself.','Follow the response procedure about stopping work and isolation.','Do not reset or erase the device unless authorised; evidence may be lost.']]
],takeaway:'Controls on. Approved tools. Prompt loss and incident reports.'},
{id:'incidents',title:'Report early, report clearly',minutes:7,sources:['S2','S5','S6','S7','S8'],goal:'Make a useful report without investigating or spreading the incident.',sections:[
['You do not need proof','Report suspicious sign-ins, lost devices, wrong recipients and suspected malware promptly. Near misses also help. Give facts and state uncertainty. A supportive reporting culture helps people ask for help early.',['Use the urgent route when immediate action is needed.','Use a known alternative if your normal account may be compromised.','Do not keep opening a suspicious file to prove the problem.']],
['Stop further harm without destroying evidence','Stop the risky activity and follow the incident procedure. Follow instructions on isolation or disconnection if malware is suspected. Do not reset devices, erase evidence, make ransom decisions or contact an attacker yourself. Ransom decisions require senior management authorisation and specialist advice.',['Record time, account or device and actions taken.','Preserve the original message through the approved reporting tool.','Keep secrets and unnecessary personal data out of reports.']],
['A short factual report is enough to start','Tell the team what happened, when, where, which service or device, what may be involved and what you have done. "I entered my password at 14:10" is more useful than "I was hacked." The authorised team handles investigation and external communication.',['Include whether you approved MFA, downloaded or ran a file, or sent data.','Do not broadcast suspected incident material.','Fraud involving payment needs urgent escalation.']]
],takeaway:'Stop. Trusted reporting route. Facts, not secrets.'},
{id:'law',title:'Know your part, know the limits',minutes:6,sources:['S7','S8','S9','S10','S11'],goal:'Separate prompt staff reporting from legal notification and certification.',sections:[
['The organisation assesses the breach','Under UK GDPR, reportable personal data breaches must be notified to the ICO without undue delay and, where feasible, within 72 hours of the organisation becoming aware. ICO notification is required unless the breach is unlikely to result in a risk to people\'s rights and freedoms. Where a breach is likely to result in a high risk, affected individuals must also be informed without undue delay.',['Staff report internally promptly; 72 hours is not a waiting period.','The authorised team makes notification decisions.','The organisation records personal data breaches and its decisions, even where ICO notification is not required.']],
['Current rules, not a forecast','Law and guidance checked on 6 October 2026. The Data (Use and Access) Act 2025 changes data protection law; it does not remove the need for secure handling or prompt incident reporting. ICO guidance notes that the PECR breach-reporting timescale for communications service providers changed from 24 to 72 hours. That is a separate regime, not a universal staff deadline.',['Sector rules and contracts may add obligations; this is general awareness, not legal advice.','The Cyber Security and Resilience (Network and Information Systems) Bill is still going through Parliament as of 6 October 2026. It is not law. Its proposed main duties concern essential services and certain digital and managed service providers, not ordinary SME staff.','No unconfirmed 2027 rule is presented as law. Recheck official guidance before future rollout, with a planned review after 26 October 2026.']],
['Learning is not certification','Cyber Essentials is a separate certification scheme centred on technical controls. This course supports staff habits but does not certify the business, confer accreditation or guarantee compliance. A local completion record is not independently verified.',['Managers must still arrange appropriate technical controls and response capability.','Know your local reporting contacts, sharing rules and approved tools.','Ask for clarification if local instructions are missing or conflict.']]
],takeaway:'Report promptly. Let the authorised team assess. Learning is not certification.'}
];
