// Fictional message cards. All .invalid addresses are non-deliverable examples.
const ARTIFACTS={
workspace:{kind:'system',label:'Network portal',heading:'Station Guest Wi-Fi',lines:['Before you connect, install Station Secure Profile.','This profile is required to use our free network.'],detail:'A network portal is not an approved IT installation route.'},
payroll:{kind:'email',label:'Email preview',heading:'Payroll correction required today',lines:['From: Payroll Team <payroll-alerts@workplace-pay.invalid>','Your salary may be held unless you verify your details by 17:00.','Scan the code below and sign in with your work account.'],detail:'The training QR placeholder is not a real code and has no destination.',qr:true},
mfa:{kind:'call',label:'Call transcript',heading:'"IT Support"',lines:['Caller: "We are working on your account. Those prompts are expected."','Caller: "Approve one and I can stop the alerts."','Device: Sign-in request. Did you try to sign in?'],detail:'This is text-only simulation. No call or approval is sent.'},
supplier:{kind:'email',label:'Supplier thread + voice note',heading:'Invoice payment: revised bank account',lines:['From: Accounts <accounts@supplier.invalid>','Please use the replacement bank details today. The old account is closing.','Voice note: "It is me. We need this paid. Skip the call-back just this once."'],detail:'No bank details or payment controls are live in the simulation.'},
ai:{kind:'chat',label:'Team chat',heading:'Jamie · Customer support',lines:['"Can you summarise these tickets in that free AI tool?"','"Take the names out. It will save us half an hour."','Attached: Customer-support-export.xlsx (fictional)'],detail:'No file is attached or uploaded.'},
wrongrecipient:{kind:'email',label:'Sent item',heading:'Staff payment information',lines:['To: Alex Green <alex.green@external.invalid>','Attachment: Staff-payments.xlsx (fictional)','You meant to choose Alex Grant from the internal team.'],detail:'A similar name in autocomplete can lead to a different person.'},
converter:{kind:'system',label:'Installation notice',heading:'QuickFile Converter',lines:['Disable real-time protection to avoid installation conflicts.','Run the installer with administrator privileges.','Allow changes to this device?'],detail:'No real installer or download is provided.'},
lost:{kind:'chat',label:'Team chat',heading:'Sam · Travelling colleague',lines:['"I think the laptop is still in the taxi."','"It is password-protected. Can we leave it until tomorrow?"','"I cannot get into work email without it."'],detail:'A backup reporting route should not depend on the missing device.'},
report:{kind:'chat',label:'Team chat',heading:'Taylor · Customer operations',lines:['"I clicked the login link at 15:32. I entered my work password."','"I did not approve MFA or download anything."','"Can you help me tell someone? I am embarrassed."'],detail:'Practice helping someone report facts without collecting their password.'},
law:{kind:'chat',label:'Manager chat',heading:'Morgan · Team manager',lines:['"A customer file went to the wrong person."','"GDPR gives us 72 hours, so can we pick this up on Monday?"','"Will passing the course make us Cyber Essentials certified?"'],detail:'Staff reporting, legal notification and certification are separate.'}
};
const TRIAGE=[
{id:'normal',type:'routine',from:'Known team calendar',text:'The weekly team meeting is in your normal calendar at the usual time. No new link, file, payment, sign-in or permission change is requested.',answer:0,feedback:'Use the normal calendar route. This ordinary task does not need a security escalation just because it is online. Stay alert if the requested action changes.'},
{id:'link',type:'verify',from:'A colleague\'s chat account',text:'"I moved the project files to a new site. Sign in here now or you will lose access." You did not expect a move.',answer:1,feedback:'Verify the change using the normal project service or an established independent contact. A familiar account can be compromised.'},
{id:'mfa',type:'urgent',from:'Your sign-in app',text:'You accidentally approved a prompt you did not start. The service name is your work email.',answer:2,feedback:'Report promptly through a trusted route. The team may need to address sessions as well as credentials.'},
{id:'update',type:'routine',from:'Your managed device',text:'A security update is offered through the normal organisation-managed update process. You recognise that process and have no conflicting warning.',answer:0,feedback:'Follow the approved update process. Do not delay every update out of fear; raise unusual prompts or repeated failures with IT.'},
{id:'bank',type:'verify',from:'Supplier thread',text:'"New bank details attached. Use the phone number below to verify them. Payment must be today."',answer:1,feedback:'Use the established supplier contact and approval process, not the number supplied by this request. If payment has already moved, escalate urgently.'},
{id:'lost',type:'urgent',from:'Travelling colleague',text:'A work laptop is missing. The colleague does not know whether it has been stolen or left behind.',answer:2,feedback:'Report promptly even without proof of theft. The team can assess containment while the search continues.'}
];
const TRIAGE_LABELS=['Continue through the normal approved route','Pause and verify before acting','Report promptly through the trusted incident route'];
// Different safe outcomes are valid. Earlier choices produce later work, not a moral score.
EVENTS[0].nodes.safe={text:'Your approved connection works, but nearby passengers can see the screen. The proposal is due shortly. Both of these routes respect policy. Which suits the situation?',choices:[['Use the station\'s private work booth, confirm it is suitable, then send through the approved route.','private'],['Tell the manager the safe setup is unavailable and agree a short delay.','defer']]};
EVENTS[0].nodes.private={text:'You check the booth is private enough for the information, keep the laptop with you and send through the approved route. You spend a few minutes arranging the space, but the proposal goes out safely.',end:true,lesson:'A safe decision can include getting the work done, not only stopping it.'};
EVENTS[0].nodes.defer={text:'You tell the manager what is blocked and agree to send from a suitable location after arrival. The manager must update the customer, but there is no hidden workaround.',end:true,lesson:'A visible delay lets the business manage the deadline. It is a reasonable tradeoff when a safe setup is not available.'};
EVENTS[4].intro='Jamie asks you to prepare a three-point update from the customer-support dashboard. You normally handle this each Wednesday. The record is in the approved work system, the request is in your established team chat, and the update goes to the usual authorised team. No new sign-in link, payment, permission change or new recipient is involved.';
EVENTS[4].start='legitimate';
EVENTS[4].nodes.legitimate={text:'This is expected work through the established route. What is a proportionate next step?',choices:[['Open the approved dashboard through the usual route and prepare only the needed summary.','routine'],['Report it as an incident only because it arrived in chat.','overreport'],['Send the full export to the whole business so nobody misses context.','overshare']]};
EVENTS[4].nodes.overreport={text:'You can ask about any concern, but the provided facts do not identify an unusual security request. Treating every routine task as an incident adds work without resolving a specific risk.',choices:[['Continue through the approved workflow, watching for any change in the request.','routine']]};
EVENTS[4].nodes.overshare={text:'Routine work does not justify a wider audience or more data than needed. Keep the update to the authorised group and task.',choices:[['Prepare a limited summary in the approved workflow.','routine']]};
EVENTS[4].nodes.routine={text:'You open the real dashboard. The normal summary is possible. Jamie then suggests a new free AI tool to speed it up, using the export that includes customer health details.',choices:[['Check the tool and data-handling approval before using the export.','approved'],['Remove the names and paste the export into the new tool.','names'],['Use your personal account for the tool.','personal']]};
EVENTS[4].nodes.start=EVENTS[4].nodes.routine;
EVENTS[3].nodes.verify={text:'The established supplier contact is unavailable. The requester says the contract is at risk. Two controlled routes are available; choose the one you would use here.',choices:[['Hold the payment and escalate to the authorised approver, explaining the deadline.','hold'],['Ask the authorised approver to use the agreed backup verification route.','backup'],['Send a smaller test payment while waiting.','test']]};
EVENTS[3].nodes.hold={text:'You hold the payment and record the reason. The approver agrees to contact the supplier when the established contact is available. The customer-facing team may need to explain a delay.',end:true,lesson:'Holding a payment is a valid choice when required verification cannot be completed. Make the delay visible.'};
EVENTS[3].nodes.backup={text:'The authorised approver uses the pre-agreed backup verification route, checks the bank change and keeps the required approval record. The verified instruction is processed without using the number in the suspicious request.',end:true,lesson:'A documented backup process can keep work moving. It must already be approved, not invented by the requester.'};
ARTIFACTS.ai={kind:'chat',label:'Established team chat',heading:'Jamie · Customer support',lines:['"Could you prepare the usual three-point update in the support dashboard?"','"Same authorised group as last Wednesday. No full export needed."','Later: "Would a new AI tool make it quicker?"'],detail:'The routine request and the new-tool suggestion are different decisions.'};
const FOLLOWUPS={
workspace:{defer:{at:'ai',heading:'Customer update: deadline adjusted',text:'Your manager used the delay you raised at 08:45 to update the customer. The proposal remains in the approved system. A visible delay created coordination work, not a hidden exposure.'},private:{at:'ai',heading:'Customer update: proposal received',text:'The proposal sent from the checked private booth is received. The team can continue from the approved system. Your earlier choice kept work moving without an unapproved route.'}},
payroll:{recover:{at:'report',heading:'IT follow-up: your earlier payroll report',text:'Because you reported entering a password earlier, the response team had the facts needed to direct recovery and assess session access. The earlier exposure was real within the simulation; it was not undone simply by reaching a safer answer.'},done:{at:'report',heading:'HR follow-up: similar messages received',text:'Your earlier payroll report helped the team connect similar messages from other staff. Independent checking prevented the sign-in exposure in your route. The reporting habit helps more than one person.'}},
supplier:{hold:{at:'law',heading:'Accounts follow-up: a payment still needs an owner',text:'Your earlier payment hold is still with the authorised approver. The delay is recorded and the supplier contact is being checked. Security decisions can leave real operational work for someone to own.'},backup:{at:'law',heading:'Accounts follow-up: backup process used',text:'The approver completed the pre-agreed backup verification route and recorded the decision. A safe backup process kept the payment moving without relying on the requester\'s new phone number.'},recover:{at:'law',heading:'Accounts follow-up: possible payment loss',text:'The authorised team contacted the bank after the earlier transfer. Recovery is not guaranteed. Your prompt report supported the response, but a later correct choice does not erase the possible financial loss.'}},
converter:{recover:{at:'lost',heading:'IT follow-up: device investigation continues',text:'Your earlier installer route triggered an investigation. The response team is handling the device and recovery. This work continues beyond the moment you stopped experimenting.'}}
};

// Remove superseded routes so every shipped node belongs to a playable path.
delete EVENTS[0].nodes.screen;delete EVENTS[0].nodes.done;delete EVENTS[3].nodes.id;delete EVENTS[4].nodes.start;

EVENTS[4].subject='The usual support update';EVENTS[4].from='Jamie · Customer support';
