// Fictional message cards. All .invalid addresses are non-deliverable examples.
const ARTIFACTS={
workspace:{kind:'system',label:"Page asking you to join the network",heading:'Station Guest Wi-Fi',lines:["Before you connect, install these Station Secure settings.","These settings are required to use our free network."],detail:"A page asking you to join the network is not approval from your work computer support team to install anything."},
payroll:{kind:'email',label:'Email preview',heading:'Payroll correction required today',lines:['From: Payroll Team <payroll-alerts@workplace-pay.invalid>',"Your salary may be held unless you check your details by 17:00.",'Scan the code below and sign in with your work account.'],detail:"The training example scanning code is not a real code and has no destination.",qr:true},
mfa:{kind:'call',label:'Call transcript',heading:"\"Work computer support\"",lines:["Caller: \"We are working on your account. Those sign-in requests are expected.\"",'Caller: "Approve one and I can stop the alerts."','Device: Sign-in request. Did you try to sign in?'],detail:"This is fictional text for practice. No call or approval is sent."},
supplier:{kind:'email',label:"Supplier conversation + voice note",heading:'Invoice payment: revised bank account',lines:['From: Accounts <accounts@supplier.invalid>','Please use the replacement bank details today. The old account is closing.',"Voice note: \"It is me. We need this paid. Skip the call using an established phone number just this once.\""],detail:'No bank details or payment controls are live in the simulation.'},
ai:{kind:'chat',label:'Team chat',heading:'Jamie · Customer support',lines:["\"Can you summarise these tickets in that free automatic writing tool?\"",'"Take the names out. It will save us half an hour."','Attached: Customer-support-export.xlsx (fictional)'],detail:'No file is attached or uploaded.'},
wrongrecipient:{kind:'email',label:'Sent item',heading:'Staff payment information',lines:['To: Alex Green <alex.green@external.invalid>','Attachment: Staff-payments.xlsx (fictional)','You meant to choose Alex Grant from the internal team.'],detail:"A similar name in the address suggestions can lead to a different person."},
converter:{kind:'system',label:'Installation notice',heading:'QuickFile Converter',lines:["Disable protection that checks for harmful software as you work to avoid installation conflicts.","Run the installation file with permission to change important device settings.",'Allow changes to this device?'],detail:'No real installer or download is provided.'},
lost:{kind:'chat',label:'Team chat',heading:'Sam · Travelling colleague',lines:['"I think the laptop is still in the taxi."','"It is password-protected. Can we leave it until tomorrow?"','"I cannot get into work email without it."'],detail:'A backup reporting route should not depend on the missing device.'},
report:{kind:'chat',label:'Team chat',heading:'Taylor · Customer operations',lines:['"I clicked the login link at 15:32. I entered my work password."',"\"I did not approve an extra sign-in check or download anything.\"",'"Can you help me tell someone? I am embarrassed."'],detail:'Practice helping someone report facts without collecting their password.'},
law:{kind:'chat',label:'Manager chat',heading:'Morgan · Team manager',lines:['"A customer file went to the wrong person."',"\"Data protection law gives us 72 hours, so can we pick this up on Monday?\"","\"Will passing the course make us approved under the separate Cyber Essentials scheme?\""],detail:"Staff reporting, telling people outside the organisation and formal approval are separate decisions."}
};
const TRIAGE=[
{id:'normal',type:'routine',from:'Known team calendar',text:'The weekly team meeting is in your normal calendar at the usual time. No new link, file, payment, sign-in or permission change is requested.',answer:0,feedback:"Use the normal calendar route. This ordinary task does not need a security report just because it is online. Stay alert if the requested action changes."},
{id:'link',type:'verify',from:'A colleague\'s chat account',text:'"I moved the project files to a new site. Sign in here now or you will lose access." You did not expect a move.',answer:1,feedback:"Check the change using the normal project service or an established independent contact. A familiar account can be accessed or controlled without permission."},
{id:'mfa',type:'urgent',from:'Your sign-in app',text:"You accidentally approved a sign-in request you did not start. The service name is your work email.",answer:2,feedback:"Report as soon as you can through a trusted route. The team may need to sign the account out on devices or apps where it is already signed in as well as change passwords."},
{id:'update',type:'routine',from:"Your work-managed device",text:'A security update is offered through the normal organisation-managed update process. You recognise that process and have no conflicting warning.',answer:0,feedback:"Follow the approved update process. Do not delay every update out of fear; raise unusual sign-in requests or repeated failures with your work computer support team."},
{id:'bank',type:'verify',from:"Supplier conversation",text:"\"New bank details attached. Use the phone number below to check them. Payment must be today.\"",answer:1,feedback:"Use the established supplier contact and approval process, not the number supplied by this request. If payment has already moved, report urgently."},
{id:'lost',type:'urgent',from:'Travelling colleague',text:'A work laptop is missing. The colleague does not know whether it has been stolen or left behind.',answer:2,feedback:"Report as soon as you can even without proof of theft. The team can act to limit harm while the search continues."}
];
const TRIAGE_LABELS=['Continue through the normal approved route',"Pause and check before acting","Report as soon as you can through the known reporting contact"];
// Different safe outcomes are valid. Earlier choices produce later work, not a moral score.
EVENTS[0].nodes.safe={text:'Your approved connection works, but nearby passengers can see the screen. The proposal is due shortly. Both of these routes respect policy. Which suits the situation?',choices:[['Use the station\'s private work booth, confirm it is suitable, then send through the approved route.','private'],['Tell the manager the safe setup is unavailable and agree a short delay.','defer']]};
EVENTS[0].nodes.private={text:'You check the booth is private enough for the information, keep the laptop with you and send through the approved route. You spend a few minutes arranging the space, but the proposal goes out safely.',end:true,lesson:'A safe decision can include getting the work done, not only stopping it.'};
EVENTS[0].nodes.defer={text:'You tell the manager what is blocked and agree to send from a suitable location after arrival. The manager must update the customer, but there is no hidden workaround.',end:true,lesson:'A visible delay lets the business manage the deadline. It is a reasonable tradeoff when a safe setup is not available.'};
EVENTS[4].intro="Jamie asks you to prepare a three-point update from the usual customer support screen. You normally handle this each Wednesday. The record is in the approved work system, the request is in your established team chat, and the update goes to the usual approved team. No new sign-in link, payment, permission change or new recipient is involved.";
EVENTS[4].start='legitimate';
EVENTS[4].nodes.legitimate={text:"This is expected work through the established route. What is a sensible next step?",choices:[["Open the approved work screen through the usual route and prepare only the needed summary.",'routine'],["Report it as a security problem only because it arrived in chat.",'overreport'],["Send the full copy of the records to the whole business so nobody misses context.",'overshare']]};
EVENTS[4].nodes.overreport={text:"You can ask about any concern, but the provided facts do not identify an unusual security request. Treating every routine task as a security problem adds work without resolving a specific risk.",choices:[['Continue through the approved process, watching for any change in the request.','routine']]};
EVENTS[4].nodes.overshare={text:"Routine work does not justify a wider audience or more data than needed. Keep the update to the approved group and task.",choices:[['Prepare a limited summary in the approved process.','routine']]};
EVENTS[4].nodes.routine={text:"You open the real work screen. The normal summary is possible. Jamie then suggests a new free automatic writing tool to speed it up, using the downloaded copy of the records that includes customer health details.",choices:[["Check the tool and data-handling approval before using the downloaded copy of the records.",'approved'],["Remove the names and paste the downloaded copy of the records into the new tool.",'names'],['Use your personal account for the tool.','personal']]};
EVENTS[4].nodes.start=EVENTS[4].nodes.routine;
EVENTS[3].nodes.verify={text:'The established supplier contact is unavailable. The requester says the contract is at risk. Two approved routes are available; choose the one you would use here.',choices:[["Hold the payment and ask for help from the person authorised to approve payment, explaining the deadline.",'hold'],["Ask the person authorised to approve payment to use the agreed backup checking route.",'backup'],['Send a smaller test payment while waiting.','test']]};
EVENTS[3].nodes.hold={text:"You hold the payment and record the reason. The person authorised to approve payment agrees to contact the supplier when the established contact is available. The customer-facing team may need to explain a delay.",end:true,lesson:"Holding a payment is a valid choice when required checking cannot be completed. Make the delay visible."};
EVENTS[3].nodes.backup={text:"The person authorised to approve payment uses the pre-agreed backup checking route, checks the bank change and keeps the required approval record. The checked instruction is processed without using the number in the suspicious request.",end:true,lesson:'A documented backup process can keep work moving. It must already be approved, not invented by the requester.'};
ARTIFACTS.ai={kind:'chat',label:'Established team chat',heading:'Jamie · Customer support',lines:["\"Could you prepare the usual three-point update in the usual support screen?\"","\"Same approved group as last Wednesday. No full copy of the records needed.\"","Later: \"Would a new automatic writing tool make it quicker?\""],detail:'The routine request and the new-tool suggestion are different decisions.'};
const FOLLOWUPS={
workspace:{defer:{at:'ai',heading:'Customer update: deadline adjusted',text:"Your manager used the delay you raised at 08:45 to update the customer. The proposal remains in the approved system. Your manager could handle the delay without a hidden security risk."},private:{at:'ai',heading:'Customer update: proposal received',text:'The proposal sent from the checked private booth is received. The team can continue from the approved system. Your earlier choice kept work moving without an unapproved route.'}},
payroll:{recover:{at:'report',heading:"Your work computer support team follow-up: your earlier payroll report",text:"Because you reported entering a password earlier, the team responsible for handling the concern had the facts needed to restore safe access and check where the account is already signed in. The earlier possible access without permission was real within the simulation; it was not undone simply by reaching a safer answer."},done:{at:'report',heading:"Your staff/payroll team follow-up: similar messages received",text:"Your earlier payroll report helped the team connect similar messages from other staff. Checking through a trusted route kept you from giving account access in this task. The reporting habit helps more than one person."}},
supplier:{hold:{at:'law',heading:'Accounts follow-up: someone must handle the held payment',text:"Your earlier payment hold is still with the person authorised to approve payment. The delay is recorded and the supplier contact is being checked. Security decisions can leave work that someone must take responsibility for."},backup:{at:'law',heading:'Accounts follow-up: backup process used',text:"The person authorised to approve payment completed the pre-agreed backup checking route and recorded the decision. A safe backup process kept the payment moving without relying on the requester's new phone number."},recover:{at:'law',heading:'Accounts follow-up: possible payment loss',text:"The approved team contacted the bank after the earlier transfer. Recovering the money is not guaranteed. Your quick report supported the response, but a later correct choice does not erase the possible financial loss."}},
converter:{recover:{at:'lost',heading:"Your work computer support team follow-up: device investigation continues",text:"Your earlier choice to run the file led to an investigation. The team responsible for handling the concern is handling the device and restoring safe work. This work continues beyond the moment you stopped experimenting."}}
};

// Remove superseded routes so every shipped node belongs to a playable path.
delete EVENTS[0].nodes.screen;delete EVENTS[0].nodes.done;delete EVENTS[3].nodes.id;delete EVENTS[4].nodes.start;

EVENTS[4].subject='The usual support update';EVENTS[4].from='Jamie · Customer support';
