const EVENTS=[
{id:'workspace',time:'08:45',channel:'Workspace',from:'Your remote working day',subject:'A quick start at the station',module:'remote',intro:'You are covering customer operations for a small UK business. Your train is delayed and you need to send a confidential proposal. A free Wi-Fi portal says: "Install our security profile to continue."',start:'start',nodes:{
start:{text:'The proposal is due at 09:00. What do you do?',choices:[['Install the profile and send the proposal.','profile'],['Use an approved connection, or ask for a safe alternative.','safe'],['Use a shared station computer.','public']]},
profile:{text:'The profile would change trusted settings on your work device. A network portal is not IT approval. You stop before completing installation. What next?',lesson:'A deadline does not authorise new security settings.',choices:[['Ask IT for an approved route and mention the profile request.','safe'],['Disable the warning and continue.','escalate']]},
public:{text:'A shared computer is not an approved work device. Its software and sign-in session are outside your control. You have not entered any credentials yet.',lesson:'A different device can introduce different risks.',choices:[['Return to the approved device and connection policy.','safe'],['Email the file to your personal account instead.','escalate']]},
escalate:{text:'This workaround creates an unapproved route. Stop and explain the block to your manager or IT. If you already changed settings or sent data, report what happened.',choices:[['Stop the workaround and contact the known support route.','safe']]},
safe:{text:'You choose an approved connection. A passenger can still see the screen and hear your call. What do you do?',choices:[['Move to a suitable private place or defer sensitive work.','done'],['Continue because the VPN protects everything.','screen']]},
screen:{text:'A VPN does not prevent someone reading your screen or overhearing a call. Privacy depends on your surroundings too.',choices:[['Move or defer the sensitive work.','done']]},
done:{text:'You send the manager a short update about the delay and use an approved private setup. The deadline is handled without a hidden workaround.',end:true,lesson:'Approved connection and physical privacy both matter.'}
}},
{id:'payroll',time:'09:10',channel:'Inbox',from:'Payroll notifications',subject:'Action required: salary correction',module:'phishing',intro:'An email with a familiar logo says your salary may be delayed unless you scan a QR code and sign in. You expected a payslip this week.',start:'start',nodes:{
start:{text:'The message looks professional. What do you do?',choices:[['Scan the QR code and enter your password.','entered'],['Open the normal payroll portal using your bookmark.','portal'],['Reply asking whether it is genuine.','reply']]},
entered:{text:'You entered a password on a page reached through the message. This may be a credential exposure. Do not continue or wait for visible harm.',lesson:'A plausible request can still lead to a false sign-in page.',choices:[['Report what you entered, the service and time through the trusted route.','recover'],['Wait to see whether the next payslip arrives.','wait']]},
reply:{text:'The reply goes to the same source that sent the request. A reassuring answer would not independently verify it.',choices:[['Use the genuine payroll portal or directory contact instead.','portal']]},
portal:{text:'There is no correction request in the genuine portal. The email says HR is too busy for calls.',choices:[['Contact HR using the staff directory and report the message.','done'],['Use the urgent phone number in the email.','number'],['Delete it without reporting.','delete']]},
number:{text:'The email supplied that number; it could lead to the sender. Verification needs a route you already trust.',choices:[['Use the staff directory and report.','done']]},
delete:{text:'Deleting avoids this request, but a report can help protect other staff. You do not need to prove it is malicious.',choices:[['Use the approved phishing-reporting route.','done']]},
wait:{text:'Waiting gives a possible attacker more time. A prompt report helps IT act on credentials and active sessions.',choices:[['Report the action and time now, without sending the password.','recover']]},
recover:{text:'You tell IT what you entered and when, without sharing the password itself. You follow the genuine account recovery instructions. IT can consider session revocation as well as a password change.',end:true,lesson:'If you acted on a suspicious request, report promptly. A click, a password and a download need different responses.'},
done:{text:'HR checks the request through its established route. Your report helps the team warn other staff without circulating the risky QR code.',end:true,lesson:'Expected timing and good design do not authenticate a message.'}
}},
{id:'mfa',time:'09:40',channel:'Chat + phone',from:'Caller claiming to be IT',subject:'Approve the prompt to stop the alerts',module:'accounts',intro:'Three sign-in approval prompts arrive on your phone. You did not start a sign-in. A caller says they are from IT and asks you to approve one.',start:'start',nodes:{
start:{text:'The caller knows your manager\'s name. What do you do?',choices:[['Approve one so the alerts stop.','approved'],['Reject the prompts and contact the known helpdesk route.','verified'],['Read a one-time code to the caller instead.','code']]},
approved:{text:'An unexpected approval may grant account access. You cannot safely assume it was IT. Report the service, time and that you approved it.',choices:[['Use a trusted route to tell IT what happened.','recover'],['Change the password and tell nobody.','silent']]},
code:{text:'The code is also a sign-in secret. Knowing your manager\'s name does not verify the caller.',choices:[['Do not share it; contact the known helpdesk.','verified']]},
silent:{text:'A password change may not revoke every active session or undo other changes. The team needs to know the account may have been accessed.',choices:[['Report the approval and follow recovery instructions.','recover']]},
verified:{text:'The known helpdesk confirms it did not call you. Your report allows it to investigate attempted access. How will you protect future sign-ins?',choices:[['Use the approved MFA/passkey method and approve only sign-ins I start.','done'],['Turn MFA off because it is annoying.','off']]},
off:{text:'MFA adds useful protection. The problem was an unexpected request, not a reason to disable a control.',choices:[['Keep the approved method and use IT for recovery issues.','done']]},
recover:{text:'IT investigates and directs account recovery, including any session action needed. You keep codes and recovery secrets out of the report.',end:true,lesson:'Reject unexpected approvals. Report any accidental approval promptly.'},
done:{text:'You keep the approved sign-in protections. If a method becomes unavailable, you will use the official recovery process rather than a shared account.',end:true,lesson:'MFA helps, but a request still needs context.'}
}},
{id:'supplier',time:'10:30',channel:'Inbox + voice note',from:'Supplier accounts thread',subject:'New bank details, urgent payment',module:'social',intro:'A message inside a familiar supplier email thread gives new bank details. A voice note sounding like your manager says: "Pay today. Skip the check just this once."',start:'start',nodes:{
start:{text:'The voice sounds right and the contract is important. What next?',choices:[['Pay because the two messages agree.','paid'],['Verify through the established supplier and payment approval process.','verify'],['Call the new number in the email.','newnumber']]},
newnumber:{text:'The request supplied its own verifier. A convincing call to that number would not provide independent confirmation.',choices:[['Use the existing supplier contact and required approval route.','verify']]},
verify:{text:'The sender says verification will lose the contract. How do you handle the pressure?',choices:[['Escalate the urgency to the authorised approver while keeping the checks.','done'],['Send a smaller test payment.','test'],['Accept a photo ID sent by the requester.','id']]},
test:{text:'A small payment is still a financial commitment and does not verify the bank change.',choices:[['Return to verification and approval.','done']]},
id:{text:'A document from the requester cannot independently authenticate the bank change. It may be genuine, altered or stolen.',choices:[['Use the established verification process.','done']]},
paid:{text:'Money has already moved. Recovery may be time-sensitive. What do you do?',choices:[['Report urgently with transaction details so authorised staff can contact the bank.','recover'],['Send another transfer to reverse it.','again'],['Wait for the supplier to complain.','wait']]},
again:{text:'A second transfer does not reverse the first and may create more loss.',choices:[['Stop and report urgently.','recover']]},
wait:{text:'Delay can reduce recovery options. You do not need to prove fraud before raising the concern.',choices:[['Report urgently through the payment incident route.','recover']]},
recover:{text:'The authorised team contacts the bank and response staff with the transaction facts. You do not contact the suspected attacker or make further payments.',end:true,lesson:'After a possible fraudulent payment, prompt escalation matters.'},
done:{text:'The authorised approver uses an established contact to check the change. The process holds, even when the voice and thread feel familiar.',end:true,lesson:'Pressure, familiar accounts and convincing voices do not replace approval.'}
}},
{id:'ai',time:'11:30',channel:'Team chat',from:'A colleague',subject:'Can you summarise this with AI?',module:'data',intro:'A colleague asks you to paste customer support records into a free AI tool to save time. The records include names, account issues and health-related details mentioned by customers.',start:'start',nodes:{
start:{text:'What is the useful response?',choices:[['Paste it after removing the names.','names'],['Check the approved tools and data-handling rules first.','approved'],['Use a personal account so the business account is not involved.','personal']]},
names:{text:'Other details can still identify customers. Removing names is not automatically anonymisation.',choices:[['Use only an approved route and the minimum permitted data.','approved']]},
personal:{text:'A personal account still sends work information to the service. It does not remove the data-handling risk.',choices:[['Check the approved route.','approved']]},
approved:{text:'There is no approved AI route for these records. The colleague says it will take longer manually.',choices:[['Use the approved manual workflow and explain the time needed.','done'],['Paste only one record as a test.','test']]},
test:{text:'One customer record can still be a disclosure. Testing is not permission to send it.',choices:[['Use the approved manual workflow.','done']]},
done:{text:'You complete the work through the approved route and raise the need for a safe tool with the manager. No customer records are put into an unapproved service.',end:true,lesson:'New tool, new destination. Check approval and minimise data.'}
}},
{id:'wrongrecipient',time:'13:15',channel:'Sent items',from:'You notice a mistake',subject:'The nearly correct address',module:'data',intro:'You sent a spreadsheet containing staff pay and bank details. Autocomplete selected the wrong external recipient. You notice one minute later.',start:'start',nodes:{
start:{text:'What happens first?',choices:[['Delete the sent email and carry on.','delete'],['Report immediately through the data protection/incident route.','report'],['Wait to see whether the recipient opens it.','wait']]},
delete:{text:'Deleting your copy does not remove the recipient\'s copy. The exposure still needs assessment.',choices:[['Report the facts promptly.','report']]},
wait:{text:'Waiting can reduce containment options and delay the risk assessment.',choices:[['Report promptly.','report']]},
report:{text:'A recall attempt fails. The recipient promises deletion. What do you tell the response team?',choices:[['The facts, the contents involved and the containment attempts via the approved secure route.','done'],['It is resolved, so no record is needed.','promise'],['Forward the spreadsheet to all managers for advice.','broadcast']]},
promise:{text:'The deletion promise is useful information, not an automatic all-clear. The organisation still documents and assesses the event.',choices:[['Give the response team the facts.','done']]},
broadcast:{text:'A broad forward creates another disclosure. Give the authorised team only what it needs through the secure route.',choices:[['Limit the audience and follow the response instructions.','done']]},
done:{text:'The authorised team assesses the risk to staff, records the breach and decides whether external notification is required. You do not notify people or the ICO on your own.',end:true,lesson:'Report quickly. A recall or deletion promise does not end the decision process.'}
}},
{id:'converter',time:'14:10',channel:'Browser task',from:'A document conversion page',subject:'Disable protection to install',module:'devices',intro:'You need a file in a different format. A free converter asks you to disable security protection and run an installer as administrator.',start:'start',nodes:{
start:{text:'What is the safest next action?',choices:[['Run it because it is only a converter.','run'],['Stop and ask for an approved conversion route.','done'],['Move the customer document to a personal laptop.','personal']]},
personal:{text:'That creates an unapproved device and data destination. A blocked work tool is a support problem, not permission for a workaround.',choices:[['Ask IT for an approved route.','done']]},
run:{text:'You ran the tool. Files now have unfamiliar names and will not open. What next?',choices:[['Stop work, report urgently and follow the incident isolation procedure.','recover'],['Install another free tool to repair them.','repair'],['Reset the laptop before anyone sees it.','wipe']]},
repair:{text:'Another unapproved tool may worsen the incident. Do not keep experimenting.',choices:[['Stop and use the known urgent reporting route.','recover']]},
wipe:{text:'Resetting can destroy evidence and make investigation or recovery harder. Do not erase the device unless authorised.',choices:[['Leave further action to the response procedure.','recover']]},
recover:{text:'You use the known urgent route, describe what you ran and when, and follow isolation instructions. The response team directs recovery. You do not pay a ransom or reset the device yourself.',end:true,lesson:'After unexpected file changes, stop experimenting and get urgent help.'},
done:{text:'IT supplies an approved method. You complete the conversion without changing security settings or moving the data to a personal device.',end:true,lesson:'Keep controls in place and use approved software.'}
}},
{id:'lost',time:'15:00',channel:'Phone',from:'A travelling colleague',subject:'A laptop left behind',module:'incidents',intro:'A colleague thinks they left their work laptop in a taxi. They want to wait until tomorrow because it might turn up.',start:'start',nodes:{
start:{text:'What do you suggest?',choices:[['Report the loss immediately and provide the last known time and place.','report'],['Wait until tomorrow because the laptop has a password.','wait'],['Ask a local repair shop to track it.','shop']]},
wait:{text:'Device protection may reduce risk, but it does not remove the need for prompt reporting. IT can assess containment while the taxi search continues.',choices:[['Use the urgent loss reporting route now.','report']]},
shop:{text:'An outside repair shop is not the organisation\'s authorised response route and may introduce further exposure.',choices:[['Use the known helpdesk or backup contact.','report']]},
report:{text:'The colleague cannot access work email without the laptop. What now?',choices:[['Use the known backup phone/urgent contact route.','done'],['Ask a stranger to sign in to their work account for them.','stranger']]},
stranger:{text:'Do not disclose credentials or use an unapproved shared computer to regain access. A backup reporting route should not require the missing device.',choices:[['Use the known backup contact.','done']]},
done:{text:'The team gets a factual report and directs containment. The colleague follows safe steps to locate the taxi without putting themselves at risk.',end:true,lesson:'Report loss promptly even when the device may be recovered.'}
}},
{id:'report',time:'15:40',channel:'Incident desk',from:'The response coordinator',subject:'Write the useful first report',module:'incidents',intro:'A team member clicked an unexpected login link and entered their password. You are helping them make a first report. They are worried about being blamed.',start:'start',nodes:{
start:{text:'Which opening is most useful?',choices:[['"I entered my work password on a page from an unexpected email at 15:32."','facts'],['"I was definitely hacked by an overseas group."','guess'],['"Nothing happened. I only made a small mistake."','hide']]},
guess:{text:'That is a claim without evidence. The response team needs observed actions and timing first.',choices:[['State the action, time and service, and say what is uncertain.','facts']]},
hide:{text:'Minimising the facts can delay the right response. Thank the person for reporting; you do not need to assign blame.',choices:[['Describe the action and time clearly.','facts']]},
facts:{text:'What should the report include next?',choices:[['The service/device, whether MFA was approved, any downloads and actions already taken.','done'],['The password so IT can test it.','secret'],['The suspicious attachment forwarded to everyone.','spread']]},
secret:{text:'Do not disclose credentials in a report. IT needs to know a password was entered, not what it is.',choices:[['Give facts without secrets.','done']]},
spread:{text:'Use the approved reporting tool to preserve the original. Do not spread risky material or private details.',choices:[['Keep the audience to the authorised response route.','done']]},
done:{text:'The report gives the team enough to start. The person follows genuine recovery instructions. You thank them for speaking up promptly.',end:true,lesson:'Useful reports describe actions, timing and uncertainty. Supportive responses encourage earlier reporting.'}
}},
{id:'law',time:'16:30',channel:'Manager chat',from:'Team manager',subject:'We have 72 hours, right?',module:'law',intro:'A customer file was shared outside the business. The manager suggests leaving it until Monday because "GDPR gives us 72 hours".',start:'start',nodes:{
start:{text:'What is the right response?',choices:[['Wait because the deadline allows it.','wait'],['Raise it promptly with the designated response/data protection contact.','team'],['Email every customer personally now.','notify']]},
wait:{text:'The legal notification timescale is not a staff waiting period. The organisation needs time to contain, investigate and assess the risk.',choices:[['Report internally promptly.','team']]},
notify:{text:'External notification needs a coordinated authorised decision. Staff should provide facts to the designated team, not act alone.',choices:[['Use the internal response route.','team']]},
team:{text:'The team assesses a personal data breach and judges risk to people unlikely. What is still needed?',choices:[['A record of the breach and the reasoned notification decision.','record'],['Nothing; it can be forgotten.','forget'],['ICO notification is always mandatory for every incident.','always']]},
forget:{text:'Personal data breaches and notification decisions still need documenting, even where ICO notification is not required.',choices:[['Record the decision through the authorised process.','record']]},
always:{text:'The ICO notification duty depends on the risk threshold. Some incidents are not personal data breaches; some breaches do not require ICO notification. The authorised team decides and documents.',choices:[['Keep the record and risk assessment.','record']]},
record:{text:'The manager asks if everyone passing this course makes the business Cyber Essentials certified.',choices:[['No. Awareness learning and certification are separate.','done'],['Yes, if completion records are printed.','cert']]},
cert:{text:'A printed record does not confer accreditation, compliance or Cyber Essentials certification.',choices:[['Explain that technical controls and certification are separate.','done']]},
done:{text:'The manager confirms the response owner and local reporting routes. You finish the day knowing how to ask for help, not promising never to make a mistake.',end:true,lesson:'Prompt reporting, risk-based decisions and technical controls work together.'}
}}
];
const ASSESSMENT=[
{module:'remote',q:'You are on a company VPN in a cafe. A customer call includes private account details. Which is best?',options:['Choose a suitable private place or defer the sensitive call.','Continue because the VPN hides your voice.','Ask nearby people not to listen and continue.'],answer:0,why:'A VPN does not provide physical privacy for a conversation.'},
{module:'remote',q:'An unfamiliar Wi-Fi portal asks you to install a security profile on your work device. What should you do?',options:['Install it to meet the deadline.','Decline and use the approved connection policy or ask IT.','Send work files through personal email instead.'],answer:1,why:'A portal request does not authorise a change to trusted device settings.'},
{module:'phishing',q:'An unexpected chat message says a shared document needs a login. What is the strongest first check?',options:['Check whether the message uses correct grammar.','Reply asking the sender whether it is real.','Open the approved document service through your usual route and verify independently.'],answer:2,why:'An independent route avoids relying on the message for both the request and its verification.'},
{module:'phishing',q:'You opened a suspicious page but did not enter details or download anything. What should you tell the response contact?',options:['Nothing, since no incident is possible.','Report the page, time and exactly what you did.','Say you definitely lost all your accounts.'],answer:1,why:'Facts allow proportionate triage. Neither silence nor certainty without evidence is useful.'},
{module:'accounts',q:'Your work password is unique, but you unexpectedly approve a sign-in prompt. What next?',options:['Report the approval promptly using a trusted route.','Ignore it because the password is unique.','Share your password so a colleague can check it.'],answer:0,why:'An approved prompt may grant access; the response team needs the facts and may need to act on sessions.'},
{module:'accounts',q:'Your phone is unavailable and you cannot complete MFA. Which route should you use?',options:['Ask a colleague for their account.','Find a way to turn MFA off without IT.','Use the approved identity verification and recovery process.'],answer:2,why:'Recovery should restore supported access without shared credentials or bypassed controls.'},
{module:'social',q:'A caller who knows your current project asks for remote-control software to be installed. What should you do?',options:['Install it because they know private-looking details.','Verify through the known helpdesk and approved installation process.','Ask them for a photo and then install it.'],answer:1,why:'Details and a supplied photo do not independently authenticate the caller or authorise the software.'},
{module:'social',q:'A supplier bank change is urgent. The requester sends a new number for verification. Which is best?',options:['Call only that new number.','Make a small test payment.','Use the established supplier contact and required payment approvals.'],answer:2,why:'The request should not supply its own verification route. A test payment is still a payment.'},
{module:'data',q:'A file link is restricted and the recipient cannot open it. What should you do?',options:['Check the approved sharing route and intended access before changing permissions.','Make it public immediately.','Send it to a group chat instead.'],answer:0,why:'Widening access changes the audience. Confirm the route and permissions first.'},
{module:'data',q:'You sent personal data to the wrong recipient. They promise deletion. What happens next?',options:['Automatically close the incident.','Report the facts and promise to the authorised team for assessment and recording.','Forward the file widely to ask for opinions.'],answer:1,why:'The promise is relevant evidence, not proof that no risk remains.'},
{module:'devices',q:'An approved security update repeatedly fails. Which response is best?',options:['Disable updates permanently.','Assume malware protection replaces updates.','Report the failure to IT and keep the managed controls in place.'],answer:2,why:'Updates and malware protection have different roles. A repeated failure needs support.'},
{module:'devices',q:'A work laptop shows a ransom message and files will not open. What should you do?',options:['Stop work, use the urgent reporting route and follow the isolation procedure.','Reset it immediately before reporting.','Install a random recovery tool.'],answer:0,why:'The response procedure coordinates containment and evidence. Do not improvise repairs or erase evidence.'},
{module:'incidents',q:'Which opening gives an incident team useful information?',options:['"Someone definitely hacked the whole business."','"At 10:12 I entered a work password on a page reached from an unexpected email; I did not download a file."','"Here are my password and recovery codes."'],answer:1,why:'Observed actions and time help triage; unsupported claims and secrets do not.'},
{module:'incidents',q:'Your missing work laptop may be returned tomorrow. What should you do now?',options:['Wait until tomorrow.','Ask a stranger to sign into your account.','Report the loss immediately through the known contact route.'],answer:2,why:'Prompt reporting allows risk assessment and containment while the search continues.'},
{module:'law',q:'A manager says to delay internal breach reporting because the organisation has 72 hours. Which is correct?',options:['Staff should report promptly; the authorised team assesses notification without undue delay.','All staff may wait 72 hours.','Every suspicious message must be personally sent to the ICO.'],answer:0,why:'The organisational notification deadline is not a staff waiting period, and notification is risk-based.'},
{module:'law',q:'What does a passing completion record from this course show?',options:['Cyber Essentials certification for the employer.','Completion of this local learning activity and assessment, not accreditation or verified identity.','Guaranteed protection from future attacks.'],answer:1,why:'This course has no independent identity verification, accreditation or certification function.'}
];
const CHECKS={
remote:[['A VPN makes every website safe.',['True','False'],1,'A VPN does not authenticate requests or make downloads safe.'],['A colleague wants to use your signed-in work laptop.',['Lend it briefly','Use the approved access process instead'],1,'Keep identities and access controlled.']],
phishing:[['A familiar email account can be compromised.',['True','False'],0,'A familiar sender is not enough to verify an unexpected action.'],['A QR code is a trustworthy way to sign in because it avoids typed links.',['True','False'],1,'A QR code can lead to a malicious destination too.']],
accounts:[['Unexpected MFA prompts should be approved to stop the alerts.',['True','False'],1,'Reject and report prompts you did not start.'],['Work and personal accounts should reuse a memorable password.',['True','False'],1,'Unique passwords limit the effect of a breach at one service.']],
social:[['The requester\'s new phone number independently verifies their bank change.',['True','False'],1,'Use an established contact route, not one supplied by the request.'],['A convincing voice removes the need for payment approval.',['True','False'],1,'Impersonation and pressure do not replace the process.']],
data:[['Deleting your sent copy removes the recipient\'s email.',['True','False'],1,'Report the exposure and let the authorised team assess it.'],['Removing names always makes a customer record anonymous.',['True','False'],1,'Other details may still identify a person.']],
devices:[['A found USB stick should be plugged in to identify its owner.',['True','False'],1,'Use the approved lost-media process without connecting it.'],['An update that keeps failing should be raised with IT.',['True','False'],0,'Keep managed controls in place and get support.']],
incidents:[['You need proof of an attack before reporting.',['True','False'],1,'Report facts and uncertainties promptly.'],['A report should include what you did and when, but not your password.',['True','False'],0,'Actions and time help triage; secrets do not.']],
law:[['Every personal data breach must always be notified to the ICO.',['True','False'],1,'Notification depends on the risk threshold; breaches and decisions still need recording.'],['Passing this course makes an employer Cyber Essentials certified.',['True','False'],1,'Awareness training is separate from certification.']]
};
