const EVENTS=[
{id:'workspace',time:'08:45',channel:'Workspace',from:'Your remote working day',subject:'A quick start at the station',module:'remote',intro:"You are covering customer operations for a small UK business. Your train is delayed and you need to send a confidential proposal. A free page asking you to join the wireless network says: \"Install our settings that can change how your device connects or is managed to continue.\"",start:'start',nodes:{
start:{text:'The proposal is due at 09:00. What do you do?',choices:[["Install the requested settings and send the proposal.",'profile'],['Use an approved connection, or ask for a safe alternative.','safe'],['Use a shared station computer.','public']]},
profile:{text:"These settings can change how your device connects or is managed. A page asking you to join the network is not approval from your work computer support team. You stop before completing installation. What next?",lesson:'A deadline does not authorise new security settings.',choices:[["Ask your work computer support team for an approved route and mention the request to change settings.",'safe'],['Disable the warning and continue.','escalate']]},
public:{text:"A shared computer is not an approved work device. You cannot control its software or know whether someone else can see what you do. You have not entered any passwords or sign-in codes yet.",lesson:'A different device can introduce different risks.',choices:[['Return to the approved device and connection policy.','safe'],['Email the file to your personal account instead.','escalate']]},
escalate:{text:"This workaround creates an unapproved route. Stop and explain the block to your manager or your work computer support team. If you already changed settings or sent data, report what happened.",choices:[['Stop the workaround and contact the known support route.','safe']]},
safe:{text:'You choose an approved connection. A passenger can still see the screen and hear your call. What do you do?',choices:[['Move to a suitable private place or defer sensitive work.','done'],["Continue because the organisation's approved private-network connection (VPN) protects everything.",'screen']]},
screen:{text:"Your organisation's approved private-network connection (VPN) does not prevent someone reading your screen or overhearing a call. Privacy depends on your surroundings too.",choices:[['Move or defer the sensitive work.','done']]},
done:{text:'You send the manager a short update about the delay and use an approved private setup. The deadline is handled without a hidden workaround.',end:true,lesson:'Approved connection and physical privacy both matter.'}
}},
{id:'payroll',time:'09:10',channel:'Inbox',from:"Payroll messages",subject:'Action required: salary correction',module:'phishing',intro:"An email with a familiar logo says your salary may be delayed unless you scan a square scanning code and sign in. You expected a payslip this week.",start:'start',nodes:{
start:{text:'The message looks professional. What do you do?',choices:[["Scan the square scanning code and enter your password.",'entered'],["Open the normal payroll website using your bookmark.",'portal'],['Reply asking whether it is genuine.','reply']]},
entered:{text:"You entered a password on a page reached through the message. Your password may have been given to someone else. Do not continue or wait for visible harm.",lesson:'A plausible request can still lead to a false sign-in page.',choices:[['Report what you entered, the service and time through the trusted route.','recover'],['Wait to see whether the next payslip arrives.','wait']]},
reply:{text:"The reply goes to the same source that sent the request. A reassuring answer would not independently check it.",choices:[["Use the genuine payroll website or directory contact instead.",'portal']]},
portal:{text:"There is no correction request on the genuine website. The email says your staff/payroll team is too busy for calls.",choices:[["Contact your staff/payroll team using the staff directory and report the message.",'done'],['Use the urgent phone number in the email.','number'],['Delete it without reporting.','delete']]},
number:{text:'The email supplied that number; it could lead to the sender. Checking needs a route you already trust.',choices:[['Use the staff directory and report.','done']]},
delete:{text:'Deleting avoids this request, but a report can help protect other staff. You do not need to prove it is malicious.',choices:[["Use the approved route for reporting suspicious messages.",'done']]},
wait:{text:"Waiting gives a possible attacker more time. A quick report helps your work computer support team protect the account, including changing its password and signing it out on devices or apps where it is already signed in.",choices:[['Report the action and time now, without sending the password.','recover']]},
recover:{text:"You tell your work computer support team what you entered and when, without sharing the password itself. You follow the approved instructions for safely regaining access to the account. Your work computer support team can consider signing the account out on devices or apps where it is already signed in as well as a password change.",end:true,lesson:"If you acted on a suspicious request, report as soon as you can. A click, a password and a download need different responses."},
done:{text:"Your staff/payroll team checks the request through its established route. Your report helps the team warn other staff without circulating the risky square scanning code.",end:true,lesson:"Expected timing and good design do not prove the identity of a message."}
}},
{id:'mfa',time:'09:40',channel:'Chat + phone',from:"Caller claiming to be your work computer support team",subject:"Approve the sign-in request to stop the alerts?",module:'accounts',intro:"Three sign-in requests arrive on your phone. You did not start a sign-in. A caller says they are from your work computer support team and asks you to approve one.",start:'start',nodes:{
start:{text:'The caller knows your manager\'s name. What do you do?',choices:[['Approve one so the alerts stop.','approved'],["Reject the sign-in requests and contact the known work computer support route.",'verified'],['Read a one-time code to the caller instead.','code']]},
approved:{text:"An unexpected approval may grant account access. You cannot safely assume it was your work computer support team. Report the service, time and that you approved it.",choices:[["Use a trusted route to tell your work computer support team what happened.",'recover'],['Change the password and tell nobody.','silent']]},
code:{text:"The code is also a sign-in secret. Knowing your manager's name does not prove who the caller is.",choices:[['Do not share it; contact the known work computer support contact.','verified']]},
silent:{text:'Changing a password does not always sign the account out on devices or apps where it is already signed in, or undo other changes. The team needs to know the account may have been accessed.',choices:[["Report the approval and follow instructions to regain access safely.",'recover']]},
verified:{text:'The known work computer support team confirms it did not call you. Your report allows it to investigate attempted access. How will you protect future sign-ins?',choices:[["Use my approved sign-in method and approve only sign-ins I start.",'done'],["Turn the extra sign-in check off because it is annoying.",'off']]},
off:{text:"An extra sign-in check adds useful protection. The problem was an unexpected request, not a reason to turn off protection.",choices:[["Keep the approved method and use your work computer support team for problems regaining access.",'done']]},
recover:{text:"Your work computer support team investigates and directs steps to regain safe account access, including signing the account out on devices or apps where it is already signed in if needed. You keep codes and backup sign-in secrets out of the report.",end:true,lesson:"Reject unexpected approvals. Report any accidental approval as soon as you can."},
done:{text:"You keep the approved sign-in protections. If a method becomes unavailable, you will use the approved process to regain access rather than a shared account.",end:true,lesson:"An extra sign-in check helps, but only approve a sign-in you started."}
}},
{id:'supplier',time:'10:30',channel:'Inbox + voice note',from:"Supplier payment conversation",subject:'New bank details, urgent payment',module:'social',intro:"A message inside a familiar supplier email conversation gives new bank details. A voice note sounding like your manager says: \"Pay today. Skip the check just this once.\"",start:'start',nodes:{
start:{text:'The voice sounds right and the contract is important. What next?',choices:[['Pay because the two messages agree.','paid'],["Check through the established supplier and payment approval process.",'verify'],['Call the new number in the email.','newnumber']]},
newnumber:{text:'The request supplied its own way to check it. A convincing call to that number would not provide independent confirmation.',choices:[['Use the existing supplier contact and required approval route.','verify']]},
verify:{text:"The sender says checking will lose the contract. How do you handle the pressure?",choices:[["Escalate the urgency to the person authorised to approve payment while keeping the checks.",'done'],['Send a smaller test payment.','test'],['Accept a photo ID sent by the requester.','id']]},
test:{text:"A small payment is still a financial commitment and does not check the bank change.",choices:[["Return to checking and approval.",'done']]},
id:{text:"A document from the requester cannot independently prove the identity of the bank change. It may be genuine, altered or stolen.",choices:[["Use the established checking process.",'done']]},
paid:{text:'Money has already moved. Acting quickly may help recover the money. What do you do?',choices:[["Report urgently with transaction details so approved staff can contact the bank.",'recover'],['Send another transfer to reverse it.','again'],['Wait for the supplier to complain.','wait']]},
again:{text:'A second transfer does not reverse the first and may create more loss.',choices:[['Stop and report urgently.','recover']]},
wait:{text:"Delay can reduce the chance of recovering the money. You do not need to prove fraud before raising the concern.",choices:[["Report urgently through the known contact for payment concerns.",'recover']]},
recover:{text:"The approved team contacts the bank and response staff with the transaction facts. You do not contact the suspected attacker or make further payments.",end:true,lesson:"After a possible fraudulent payment, quickly passing the concern to the right person matters."},
done:{text:"The person authorised to approve payment uses an established contact to check the change. The process holds, even when the voice and conversation feel familiar.",end:true,lesson:'Pressure, familiar accounts and convincing voices do not replace approval.'}
}},
{id:'ai',time:'11:30',channel:'Team chat',from:'A colleague',subject:'Can you summarise this with AI?',module:'data',intro:"A colleague asks you to paste customer support records into a free automatic writing tool to save time. The records include names, account issues and health-related details mentioned by customers.",start:'start',nodes:{
start:{text:'What is the useful response?',choices:[['Paste it after removing the names.','names'],['Check the approved tools and data-handling rules first.','approved'],['Use a personal account so the business account is not involved.','personal']]},
names:{text:'Other details can still identify customers. Removing names does not always stop someone being identified from the other details.',choices:[["Use only an approved route and the smallest amount of information allowed for the task.",'approved']]},
personal:{text:'A personal account still sends work information to the service. It does not remove the data-handling risk.',choices:[['Check the approved route.','approved']]},
approved:{text:'This automatic writing tool is not approved for these records. The colleague says it will take longer manually.',choices:[['Use the approved manual process and explain the time needed.','done'],['Paste only one record as a test.','test']]},
test:{text:"Sharing even one customer record gives information to the service. Testing is not permission to send it.",choices:[['Use the approved manual process.','done']]},
done:{text:'You complete the work through the approved route and raise the need for a safe tool with the manager. No customer records are put into an unapproved service.',end:true,lesson:'New tool, new destination. Check approval and share only the information needed.'}
}},
{id:'wrongrecipient',time:'13:15',channel:'Sent items',from:'You notice a mistake',subject:'The nearly correct address',module:'data',intro:'You sent a spreadsheet containing staff pay and bank details. The address suggestions selected the wrong external recipient. You notice one minute later.',start:'start',nodes:{
start:{text:'What happens first?',choices:[['Delete the sent email and carry on.','delete'],["Report immediately through the known person responsible for security or personal information concerns.",'report'],['Wait to see whether the recipient opens it.','wait']]},
delete:{text:"Deleting your copy does not remove the recipient's copy. The wrong sharing still needs assessment.",choices:[["Report the facts as soon as you can.",'report']]},
wait:{text:"Waiting can make it harder to limit further harm and assess the risk.",choices:[["Report as soon as you can.",'report']]},
report:{text:"A recall attempt fails. The recipient promises deletion. What do you tell the team responsible for handling the concern?",choices:[["The facts, the contents involved and what was done to limit further harm, through the approved secure route.",'done'],['It is resolved, so no record is needed.','promise'],['Forward the spreadsheet to all managers for advice.','broadcast']]},
promise:{text:'The deletion promise is useful information, not an automatic all-clear. The organisation still documents and assesses the event.',choices:[["Give the team responsible for handling the concern the facts.",'done']]},
broadcast:{text:"A broad forward creates more unnecessary sharing. Give the approved team only what it needs through the secure route.",choices:[["Limit the people who can receive it and follow the response instructions.",'done']]},
done:{text:"The approved team assesses the risk to staff, records the personal-data breach and the reasons for its decisions and decides whether telling people outside the organisation is required. You do not contact affected people or the UK data protection regulator on your own.",end:true,lesson:'Report quickly. A recall or deletion promise does not end the decision process.'}
}},
{id:'converter',time:'14:10',channel:'Browser task',from:'A document conversion page',subject:'Disable protection to install',module:'devices',intro:"You need a file in a different format. A free converter asks you to disable security protection and run an installation file with permission to change important device settings.",start:'start',nodes:{
start:{text:'What is the safest next action?',choices:[['Run it because it is only a converter.','run'],['Stop and ask for an approved conversion route.','done'],['Move the customer document to a personal laptop.','personal']]},
personal:{text:"That creates an unapproved device and another place receiving work information. A blocked work tool is a support problem, not permission for a workaround.",choices:[["Ask your work computer support team for an approved route.",'done']]},
run:{text:'You ran the tool. Files now have unfamiliar names and will not open. What next?',choices:[["Stop work, report urgently and follow the agreed steps for disconnecting the device as instructed so a problem cannot spread.",'recover'],['Install another free tool to repair them.','repair'],['Reset the laptop before anyone sees it.','wipe']]},
repair:{text:"Another unapproved tool may worsen the security problem. Do not keep experimenting.",choices:[['Stop and use the known urgent reporting route.','recover']]},
wipe:{text:"Resetting can destroy evidence and make investigation or restoring safe work harder. Do not erase the device unless approved.",choices:[["Leave further action to the agreed steps for handling the concern.",'recover']]},
recover:{text:"You use the known urgent route, describe what you ran and when, and follow instructions for disconnecting the device. The team responsible for handling the concern directs how to restore safe work. You do not pay a demand to unlock files or reset the device yourself.",end:true,lesson:'After unexpected file changes, stop experimenting and get urgent help.'},
done:{text:"Your work computer support team supplies an approved method. You complete the conversion without changing security settings or moving the data to a personal device.",end:true,lesson:"Keep protections in place and use approved software."}
}},
{id:'lost',time:'15:00',channel:'Phone',from:'A travelling colleague',subject:'A laptop left behind',module:'incidents',intro:'A colleague thinks they left their work laptop in a taxi. They want to wait until tomorrow because it might turn up.',start:'start',nodes:{
start:{text:'What do you suggest?',choices:[['Report the loss immediately and provide the last known time and place.','report'],['Wait until tomorrow because the laptop has a password.','wait'],['Ask a local repair shop to track it.','shop']]},
wait:{text:"Device protection may reduce risk, but it does not remove the need for quick reporting. The support team can act to limit harm while the taxi search continues.",choices:[['Use the urgent loss reporting route now.','report']]},
shop:{text:"An outside repair shop is not the organisation's approved reporting route and may introduce further possible access without permission.",choices:[['Use the known work computer support contact or backup contact.','report']]},
report:{text:'The colleague cannot access work email without the laptop. What now?',choices:[['Use the known backup phone/urgent contact route.','done'],['Ask a stranger to sign in to their work account for them.','stranger']]},
stranger:{text:"Do not disclose passwords and sign-in codes or use an unapproved shared computer to regain access. A backup reporting route should not require the missing device.",choices:[['Use the known backup contact.','done']]},
done:{text:"The team gets a factual report and directs how to limit further harm. The colleague follows safe steps to locate the taxi without putting themselves at risk.",end:true,lesson:"Report loss as soon as you can even when the device may be recovered."}
}},
{id:'report',time:'15:40',channel:"Security reporting desk",from:"The person receiving the report",subject:'Write the useful first report',module:'incidents',intro:'A team member clicked an unexpected login link and entered their password. You are helping them make a first report. They are worried about being blamed.',start:'start',nodes:{
start:{text:'Which opening is most useful?',choices:[['"I entered my work password on a page from an unexpected email at 15:32."','facts'],['"I was definitely hacked by an overseas group."','guess'],['"Nothing happened. I only made a small mistake."','hide']]},
guess:{text:"That is a claim without evidence. The team responsible for handling the concern needs observed actions and timing first.",choices:[['State the action, time and service, and say what is uncertain.','facts']]},
hide:{text:'Minimising the facts can delay the right response. Thank the person for reporting; you do not need to assign blame.',choices:[['Describe the action and time clearly.','facts']]},
facts:{text:'What should the report include next?',choices:[["The service or device, whether an extra sign-in check was approved, any downloads and actions already taken.",'done'],["The password so your work computer support team can test it.",'secret'],['The suspicious attachment forwarded to everyone.','spread']]},
secret:{text:"Do not disclose passwords and sign-in codes in a report. Your work computer support team needs to know a password was entered, not what it is.",choices:[['Give facts without secrets.','done']]},
spread:{text:'Use the approved reporting tool to preserve the original. Do not spread risky material or private details.',choices:[["Share it only with the team responsible for handling the concern.",'done']]},
done:{text:"The report gives the team enough to start. The person follows instructions for safely regaining access. You thank them for speaking up quickly.",end:true,lesson:'Useful reports describe actions, timing and uncertainty. Supportive responses encourage earlier reporting.'}
}},
{id:'law',time:'16:30',channel:'Manager chat',from:'Team manager',subject:'We have 72 hours, right?',module:'law',intro:"A customer file was shared outside the business. The manager suggests leaving it until Monday because \"Data protection law gives us 72 hours\".",start:'start',nodes:{
start:{text:'What is the right response?',choices:[['Wait because the deadline allows it.','wait'],["Raise it as soon as you can with the known person responsible for security or personal information concerns.",'team'],['Email every customer personally now.','notify']]},
wait:{text:"The deadline for telling the regulator is not a staff waiting period. The organisation needs time to limit harm, find out what happened and assess the risk.",choices:[["Report internally as soon as you can.",'team']]},
notify:{text:"The approved team must decide who outside the organisation needs to be told. Staff should provide facts to the designated team, not act alone.",choices:[["Use the internal reporting route.",'team']]},
team:{text:"The team assesses a personal-data breach for the organisation deciding why and how the information is used. It judges a risk to people's rights and freedoms unlikely. What is still needed?",choices:[["A record of the personal-data breach and the reasons for the deciding organisation's decisions, even when no regulator report is needed.",'record'],['Nothing; it can be forgotten.','forget'],["Every security problem must always be reported to the UK data protection regulator.",'always']]},
forget:{text:"The organisation deciding why and how the information is used records every personal-data breach and the reasons for its decisions, even when it does not need to tell the regulator.",choices:[["Record the decision through the approved process.",'record']]},
always:{text:"The duty to tell the UK data protection regulator depends on the risk to people. Some security problems do not involve personal information. Some personal-data breaches do not need to be reported to the regulator. The organisation deciding why and how the information is used records every personal-data breach and the reasons for its decisions, even when it does not need to tell the regulator.",choices:[['Keep the record and risk assessment.','record']]},
record:{text:"The manager asks if everyone passing this course makes the business approved under the separate Cyber Essentials scheme.",choices:[["No. Awareness learning and formal approval are separate.",'done'],['Yes, if completion records are printed.','cert']]},
cert:{text:"A printed record does not give official recognition, compliance or formal Cyber Essentials approval.",choices:[["Explain that security protections on computers and accounts and formal approval are separate.",'done']]},
done:{text:"The manager confirms the person responsible for handling the concern and local reporting routes. You finish the day knowing how to ask for help, without promising never to make a mistake.",end:true,lesson:"Quick reporting, decisions based on the likely harm to people and security protections on computers and accounts work together."}
}}
];
const ASSESSMENT=[
{module:'remote',q:"You are on a work-approved private-network connection (VPN) in a cafe. A customer call includes private account details. Which is best?",options:['Choose a suitable private place or defer the sensitive call.',"Continue because the organisation's approved private-network connection (VPN) hides your voice.",'Ask nearby people not to listen and continue.'],answer:0,why:"Your organisation's approved private-network connection (VPN) does not provide physical privacy for a conversation."},
{module:'remote',q:"An unfamiliar page asking you to join the wireless network asks you to install settings that can change how your device connects or is managed on your work device. What should you do?",options:['Install it to meet the deadline.',"Decline and use the approved connection policy or ask your work computer support team.",'Send work files through personal email instead.'],answer:1,why:"A request on the page asking you to join the network does not authorise a change to trusted device settings."},
{module:'phishing',q:'An unexpected chat message says a shared document needs a login. What is the strongest first check?',options:['Check whether the message uses correct grammar.','Reply asking the sender whether it is real.',"Open the approved document service through your usual route and check independently."],answer:2,why:"An independent route avoids relying on the message for both the request and its checking."},
{module:'phishing',q:"You opened a suspicious page but did not enter details or download anything. What should you tell the reporting contact?",options:["Nothing, since no security problem is possible.",'Report the page, time and exactly what you did.','Say you definitely lost all your accounts.'],answer:1,why:"The facts help the team decide what action is needed. Neither silence nor certainty without evidence is useful."},
{module:'accounts',q:"Your work password is unique, but you unexpectedly approve a sign-in request you did not start. What next?",options:["Report the approval as soon as you can using a trusted route.",'Ignore it because the password is unique.','Share your password so a colleague can check it.'],answer:0,why:"Approving an unexpected sign-in request may let someone into the account; the team responsible for handling the concern needs the facts and may need to sign the account out on other devices or apps."},
{module:'accounts',q:"Your phone is unavailable and you cannot complete an extra sign-in check. Which route should you use?",options:['Ask a colleague for their account.',"Find a way to turn the extra sign-in check off without your work computer support team.","Use the approved way to prove who you are and regain access."],answer:2,why:"Recovery should restore safe access without sharing passwords or codes, or bypassing protections."},
{module:'social',q:"A caller who knows your current project asks for software that lets someone control your device from elsewhere to be installed. What should you do?",options:['Install it because they know private-looking details.',"Check through the known work computer support contact and approved installation process.",'Ask them for a photo and then install it.'],answer:1,why:"Details and a supplied photo do not independently prove the identity of the caller or authorise the software."},
{module:'social',q:"A supplier bank change is urgent. The requester sends a new number for checking. Which is best?",options:['Call only that new number.','Make a small test payment.','Use the established supplier contact and required payment approvals.'],answer:2,why:"The request should not supply its own checking route. A test payment is still a payment."},
{module:'data',q:'A file link is restricted and the recipient cannot open it. What should you do?',options:['Check the approved sharing route and intended access before changing permissions.','Make it public immediately.','Send it to a group chat instead.'],answer:0,why:"Widening access changes the people who can receive it. Confirm the route and permissions first."},
{module:'data',q:"You sent personal information to the wrong recipient. They promise deletion. What happens next?",options:["Automatically close the security problem.","Report the facts and promise to the approved team for assessment and recording.",'Forward the file widely to ask for opinions.'],answer:1,why:'The promise is relevant evidence, not proof that no risk remains.'},
{module:'devices',q:'An approved security update repeatedly fails. Which response is best?',options:['Disable updates permanently.',"Assume harmful software protection replaces updates.","Report the failure to your work computer support team and keep the approved protections in place."],answer:2,why:"Updates and harmful software protection have different roles. A repeated failure needs support."},
{module:'devices',q:"A work laptop shows a message demanding money to unlock files and files will not open. What should you do?",options:["Stop work, use the urgent reporting route and follow the agreed steps for disconnecting the device.",'Reset it immediately before reporting.',"Install a random repair tool."],answer:0,why:"The agreed procedure helps stop the problem spreading while keeping evidence. Do not improvise repairs or erase evidence."},
{module:'incidents',q:"Which opening gives the team handling a security concern useful information?",options:['"Someone definitely hacked the whole business."','"At 10:12 I entered a work password on a page reached from an unexpected email; I did not download a file."',"\"Here are my password and backup sign-in codes.\""],answer:1,why:"Observed actions and time help decide what needs attention; unsupported claims and secrets do not."},
{module:'incidents',q:'Your missing work laptop may be returned tomorrow. What should you do now?',options:['Wait until tomorrow.','Ask a stranger to sign into your account.','Report the loss immediately through the known contact route.'],answer:2,why:"Quick reporting allows risk assessment and stopping the problem spreading while the search continues."},
{module:'law',q:"A manager says to delay internal personal information problem reporting because the organisation has 72 hours. Which is correct?",options:["Staff should report quickly; the approved team assesses whether anyone outside the organisation must be told.",'All staff may wait 72 hours.',"Every suspicious message must be personally sent to the UK data protection regulator."],answer:0,why:"The organisation's deadline for telling the regulator is not a staff waiting period, and telling the regulator is based on the likely harm to people."},
{module:'law',q:'What does a passing completion record from this course show?',options:["Formal approval for the employer under the separate Cyber Essentials scheme.","Completion of this local learning activity and assessment, not official recognition or checked identity.",'Guaranteed protection from future attacks.'],answer:1,why:"This course does not independently check who completed it or provide an officially recognised qualification or approval."}
];
const CHECKS={
remote:[["Your organisation's approved private-network connection (VPN) makes every website safe.",['True','False'],1,"Your organisation's approved private-network connection (VPN) does not prove the identity of requests or make downloads safe."],['A colleague wants to use your signed-in work laptop.',['Lend it briefly','Use the approved access process instead'],1,"Each person should use their own approved sign-in. Do not lend access to your account."]],
phishing:[["A familiar email account can be accessed or controlled without permission.",['True','False'],0,"A familiar sender is not enough to check an unexpected action."],["A square scanning code is a trustworthy way to sign in because it avoids typed links.",['True','False'],1,"A square scanning code can lead to a harmful website too."]],
accounts:[["Unexpected requests for an extra sign-in check should be approved to stop the alerts.",['True','False'],1,"Reject and report sign-in requests you did not start."],['Work and personal accounts should reuse a memorable password.',['True','False'],1,"Different passwords limit the harm if a password at one service is stolen."]],
social:[["The requester's new phone number independently checks their bank change.",['True','False'],1,'Use an established contact route, not one supplied by the request.'],['A convincing voice removes the need for payment approval.',['True','False'],1,"Pretending to be someone else or pressuring you does not replace the required checks."]],
data:[['Deleting your sent copy removes the recipient\'s email.',['True','False'],1,"Report the wrong sharing and let the approved team assess it."],["Removing names always stops anyone being identified from a customer record.",['True','False'],1,'Other details may still identify a person.']],
devices:[["A found memory stick that plugs into a computer should be plugged in to identify its owner.",['True','False'],1,"Use the approved process for found or lost storage devices without connecting it."],["An update that keeps failing should be reported to your work computer support team.",['True','False'],0,"Keep the approved protections in place and get support."]],
incidents:[['You need proof of an attack before reporting.',['True','False'],1,"Report facts and uncertainties as soon as you can."],['A report should include what you did and when, but not your password.',['True','False'],0,"Actions and time help decide what needs attention; secrets do not."]],
law:[["Every personal-data breach must always be reported to the UK data protection regulator.",['True','False'],1,"Whether the regulator must be told depends on risk to people. The organisation deciding why and how the information is used records every personal-data breach and the reasons for its decisions, even when it does not need to tell the regulator."],["Passing this course gives an employer approval under the separate Cyber Essentials scheme.",['True','False'],1,"Awareness training is separate from formal approval."]]
};
